In [1]:
import numpy as np
import matplotlib as mpl
from matplotlib import pyplot as plt
from matplotlib.gridspec import GridSpec
import CompleteHist as ch
import Analysis
%matplotlib

Using matplotlib backend: TkAgg


In [2]:
%matplotlib

Using matplotlib backend: TkAgg


In [3]:
from matplotlib.colors import LinearSegmentedColormap
def get_axis_limits(ax, xscale=-1.01, yscale=1.0):
    return ax.get_xlim()[1]*xscale, ax.get_ylim()[1]*yscale

def phase_switch(data,minus=0):
    temp = list()
    temp.append(np.array(data[0]))
    flip = True
    for i in range(1,len(data)):
        temp.append(np.array(data[i]))
        if data[i-1][1] == data[i][1] and data[i-1][2] == data[i][2]:
            if flip:
                temp[-1][2] = 2*(1 - minus) - temp[-1][2]
                flip = False
            else:
                flip = True
        else:
            flip = True
    return np.array(temp)

In [4]:
x = np.linspace(0,2*np.pi,1000)
y = np.sin(x)
plt.plot(x,y,c='k')
y = np.sin(x+np.pi/4)
plt.plot(x,y,c='r')

In [5]:
plt.rc('text', usetex=True) 

# Helvetica 
# set serif, too. Otherwise setting to times and then 
# Helvetica causes an error. 
font = {'family':'sans-serif','sans-serif':['Helvetica'], 
        'serif':['cm10']} 
preamble  = r""" 
               \usepackage{color} 
               \usepackage[tx]{sfmath} 
               \usepackage{helvet} 
            """ 


# Unicode for Tex 
#preamble =  r"""\usepackage[utf8]{inputenc}""" + preamble 
# inputenc should be set automatically 
plt.rcParams['text.latex.unicode']=True 

#print font, preamble 
plt.rc('font',**font) 
plt.rcParams['text.latex.preamble'] = preamble
mpl.rcParams.update({'font.size': 11})

In [6]:
#plotting from 0:2pi
#Current Color Scheme!!!!!
cdict = {'red': ((0.0, 0.0, 0.0),
                 (0.25, 0.0, 0.0),
                   (0.375, 1.0, 1.0),
                   (0.5, 1.0, 1.0),
                   (0.625, 1.0, 1.0),
                  (1.0, 0.5, 0.5)),

         'green': ((0.0, 1, 1),
                   (0.125, 0.0, 0.0),
                   (0.25, 1.0, 1.0),
                   (0.5, 0.0, 0.0),
                   (0.625, 1.0, 1.0),
                  (1.0, 1, 1)),

         'blue': ((0.0, 0.0, 0.0),
                   (0.125, 1.0, 1.0),
                   (0.25, 1.0, 1.0),
                   (0.375, 1.0, 1.0),
                   (0.5, 0.0, 0.0),
                   (1.0, 0.0, 0.0)),
        }
        
fullC = LinearSegmentedColormap('fullC', cdict)

In [12]:
pruned14 = np.load('Pruned 025 4_16_2019.npy')
pruned34 = np.load('Pruned 075 6_6_2019.npy')
pruned12 = np.load('Pruned 05 3_12_2019.npy')
prunedfig = np.load('Pruned 1 Fig 6_6_2019.npy')
prunedsup = np.load('Pruned 1 Sup 6_6_2019.npy')

new14 = list()
for i in pruned14:
    for j in i:
        new14.append(j)
new14 = np.array(new14)

new34 = list()
for i in pruned34:
    for j in i:
        new34.append(j)
new34 = np.array(new34)

new12 = list()
for i in pruned12:
    for j in i:
        new12.append(j)
new12 = np.array(new12)


newfig = list()
for i in prunedfig:
    for j in i:
        newfig.append(j)
newfig = np.array(newfig)

newsup = list()
for i in prunedsup:
    for j in i:
        newsup.append(j)
        
newsup = np.array(newsup)


sw14 = phase_switch(new14)
sw12 = phase_switch(new12)
sw34 = phase_switch(new34)
swfig = phase_switch(newfig)
swsup = phase_switch(newsup)

In [16]:
temp = list(new14)
pi14 = np.array(temp.pop(-3))
new14 = np.array(temp)
pi = np.vstack((newsup,newfig,pi14))

pi

array([[-14.4746    ,   5.5825    ,   1.02110047,   1.        ],
       [ -7.651     ,   5.5825    ,   1.02110047,   1.        ],
       [ -7.43      ,   5.5825    ,   1.02110047,   1.        ],
       [-14.2383    ,   5.582     ,   0.99611736,   1.        ],
       [-13.8221    ,   5.5805    ,   0.9816624 ,   1.        ],
       [-13.9362    ,   5.5795    ,   0.95692798,   1.        ],
       [-13.7099    ,   5.579     ,   0.94285897,   1.        ],
       [-15.348325  ,   5.578     ,   0.91429435,   1.        ],
       [-14.955145  ,   5.578     ,   0.91429435,   1.        ],
       [-12.94725   ,   5.578     ,   0.91429435,   1.        ],
       [-21.7499    ,   5.578     ,   0.94609601,   1.        ],
       [-35.588805  ,   5.535     ,   0.94226665,   0.83892617],
       [-35.00868   ,   5.5305    ,   0.91014898,   0.89013453],
       [-34.85053   ,   5.5305    ,   0.91014898,   0.89013453],
       [-33.961335  ,   5.5305    ,   0.91014898,   0.89013453],
       [-33.723595  ,   5

In [23]:
sorted(pi[:,0])

[-41.428709999999995,
 -41.257854999999999,
 -36.534724999999995,
 -36.01296,
 -35.944099999999999,
 -35.672934999999995,
 -35.657465000000002,
 -35.588804999999994,
 -35.496290000000002,
 -35.389520000000005,
 -35.333514999999998,
 -35.216449999999995,
 -35.008679999999998,
 -34.9435,
 -34.911609999999996,
 -34.89967,
 -34.850529999999999,
 -34.804064999999994,
 -34.708945,
 -34.666044999999997,
 -34.497990000000001,
 -34.418469999999999,
 -34.154759999999996,
 -34.073705000000004,
 -34.059004999999999,
 -33.971060000000001,
 -33.968274999999998,
 -33.961334999999998,
 -33.935365000000004,
 -33.723595000000003,
 -33.722319999999996,
 -33.649999999999999,
 -33.550764999999998,
 -33.463284999999999,
 -32.311504999999997,
 -31.948504999999997,
 -31.948160000000001,
 -31.542765000000003,
 -21.7499,
 -15.348324999999999,
 -15.1785,
 -14.955145000000002,
 -14.8683,
 -14.474600000000001,
 -14.238300000000001,
 -14.167999999999999,
 -13.936199999999999,
 -13.838535,
 -13.822100000000001,
 -13

In [27]:
#Prepare DATA
pruned14 = np.load('Pruned 025 4_16_2019.npy')
pruned34 = np.load('Pruned 075 6_6_2019.npy')
pruned12 = np.load('Pruned 05 3_12_2019.npy')
prunedfig = np.load('Pruned 1 Fig 6_6_2019.npy')
prunedsup = np.load('Pruned 1 Sup 6_6_2019.npy')

new14 = list()
for i in pruned14:
    for j in i:
        new14.append(j)
new14 = np.array(new14)

new34 = list()
for i in pruned34:
    for j in i:
        new34.append(j)
new34 = np.array(new34)

new12 = list()
for i in pruned12:
    for j in i:
        new12.append(j)
new12 = np.array(new12)


newfig = list()
for i in prunedfig:
    for j in i:
        newfig.append(j)
newfig = np.array(newfig)

newsup = list()
for i in prunedsup:
    for j in i:
        newsup.append(j)
        
newsup = np.array(newsup)

temp = list(new14)
pi14 = np.array(temp.pop(-3))
new14 = np.array(temp)
pi = np.vstack((newsup,newfig,pi14))


sw14 = phase_switch(new14)
sw12 = phase_switch(new12)
sw34 = phase_switch(new34)
swfig = phase_switch(newfig)
swsup = phase_switch(newsup)
swpi = phase_switch(pi)



sw14m = phase_switch(new14,minus = 1)
pim = phase_switch(pi,minus = 1)
sw12m = phase_switch(new12, minus = 1)
sw34m = phase_switch(new34, minus = 1)
sw34m[-1][2] = sw34m[-1][2] - 2.0

In [8]:
run14 = Analysis.Run(np.load('2014_Raw.npy'), np.load('2014_Prune_strong.npy'), Analysis.bval2014, np.load('2014bf_new_prune_edit.npy'))
run11 = Analysis.Run(np.load('2011_Raw.npy'), np.load('2011_Prune_strong_flat.npy'), Analysis.bval2011, np.load('2011bf_new_prune_flat_edit.npy'))

soft11 = Analysis.Run(np.load('2011_Raw.npy'), np.load('2011_Prune_new_flat.npy'), Analysis.bval2011, np.load('2011bf_new_prune_flat_edit.npy'))
soft14 = Analysis.Run(np.load('2014_Raw.npy'), np.load('2014_Prune_new.npy'), Analysis.bval2014, np.load('2014bf_new_prune_edit.npy'))

i14 = run14.prune_data
i11 = run11.prune_data

s14 = soft14.prune_data
s11 = soft11.prune_data

array([[-30.9763    ,   5.5805    ,   0.35446229,   1.        ],
       [-30.11417   ,   5.5805    ,   1.64553771,   1.        ],
       [-28.8464    ,   5.5805    ,   0.35446229,   1.        ],
       [-26.6193    ,   5.5805    ,   1.64553771,   1.        ],
       [-27.5842    ,   5.5805    ,   0.35446229,   1.        ],
       [-25.1515    ,   5.5805    ,   0.25995879,   1.        ],
       [-25.007     ,   5.5805    ,   1.74004121,   1.        ],
       [-21.99253   ,   5.581     ,   0.24561601,   1.        ],
       [-21.041845  ,   5.581     ,   1.75438399,   1.        ],
       [-24.267575  ,   5.583     ,   0.27320272,   1.        ],
       [-23.998675  ,   5.583     ,   1.72679728,   1.        ],
       [-21.7239    ,   5.583     ,   0.27320272,   1.        ],
       [-20.24955   ,   5.583     ,   0.25      ,   1.        ],
       [-19.4861    ,   5.5835    ,   0.27931602,   1.        ],
       [-18.62333   ,   5.5835    ,   0.28183099,   1.        ],
       [-18.2212    ,   5

# Histogram

In [31]:
#All data

#Data---------------------------------------------------------------------------------
width = 0.025
offset = 0
bins = np.arange(offset,2.0,width)

data = [sw12,sw14,sw34,swpi] #BECAUSE OF DOUBLE DATA, SORT OUT WITH WOOWON FOR PI FIGURE

#-------------------------------------------------------------------------------------
colors = ['green','blue','orange','red']

fig = plt.figure(figsize=[6,3])
plt.subplot2grid((100,100), (0,0), colspan=100, rowspan=92) #for 3x6
#plt.subplot2grid((100,100), (0,0), colspan=100, rowspan=97) #for 4x6

temp = np.zeros(len(bins)-1)
for i in range(len(colors)):
    x,_ = np.histogram(data[i][:,2],bins)
    plt.bar(bins[:-1],x,bottom=temp,width=width,color=colors[i], alpha=0.8)
    temp+=x

plt.ylim(0,15)
plt.yticks([0,5,10,15])
plt.xlim(0,2)
plt.xticks([0,0.25,0.5,0.75,1,1.25,1.5,1.75,2.0])
plt.xlabel('$\Delta\\theta$($\pi$)',size=18,labelpad = 3)
plt.ylabel('Count',size=18)



In [48]:
np.mean(new12[:,2])

0.52300010271159225

In [49]:
np.std(new12[:,2])

0.021061286074864675

In [50]:
len(new12)

6

In [47]:
new12

array([[-24.66637   ,   5.5265    ,   0.47590564,   0.8836773 ],
       [-30.623075  ,   5.534     ,   0.532419  ,   0.80487805],
       [-28.549115  ,   5.534     ,   0.532419  ,   0.80487805],
       [-28.18076   ,   5.534     ,   0.532419  ,   0.80487805],
       [-27.62813   ,   5.534     ,   0.532419  ,   0.80487805],
       [-27.450285  ,   5.534     ,   0.532419  ,   0.80487805]])

In [29]:
fig.savefig('Hist 6_2019 3x6',dpi=1000)

# Paper Figures

In [ ]:
se14 = np.load('2014se_new_sign.npy')
se11 = np.load('2011se_new_sign.npy')
#use this to plot slips:
#for k in se11[n][np.abs(se11[n][:,2] - i11[n].fits[j].delta_phi)<0.01]:
    #ax5.axvline(k[0],color='k',lw=2)

In [ ]:
from matplotlib.gridspec import GridSpec
gs = GridSpec(1000,1000)

def search(data, t):
    seq = data
    min = 0
    max = len(seq) - 1
    while True:        
        m = (min + max) // 2
        if max < min:
            if np.abs(t-seq[m]) < np.abs(t-seq[m-1]):          
                return m
            else:
                return m-1        
        if seq[m] < t:
            min = m + 1
        elif seq[m] > t:
            max = m - 1
        else:
            return m

def t(y_min,y_max):
    diff = y_max-y_min
    p = float(diff)*0.35
    return y_min-p,y_max+p

def init_plot(i):
    i.plot()
    plt.xlim([min(i.x),max(i.x)])
    plt.ylim([min(i.y)-0.05,max(i.y)+0.05])
    
def stitch(i,x):
    i.fits[1].plot_select('b',['k','r'],[2,2],i.fits[1].pos_left,x)
    i.fits[0].plot_select('b',['r','#00ff00'],[2,2],x,i.fits[0].pos_right)
    
def set_axis(sweep,x_min,x_max):
    plt.xlim(x_min,x_max)
    x = np.linspace(x_min,x_max)
    yl,yr = sweep.fits[j].yValue(x)
    y_min = np.min([yl,yr])
    y_max = np.max([yl,yr])
    l,h = t(y_min,y_max)
    plt.ylim(l,h)
    plt.yticks([y_min,y_max],(round(y_min,1),round(y_max,1)))
    x_low, x_high = np.percentile(x,[25,75])
    plt.xticks([int(x_low),int(x_high)])

def newSE(run,se,fit_list,k,_a,_b):
    temp = list()
    j = fit_list[k][1]
    n = fit_list[k][0]
    for k in se[n][np.abs(se[n][:,2] - (run.prune_data[n].fits[j].phase_r-run.prune_data[n].fits[j].phase_l)/np.pi%2)<0.001]:
        temp.append(k)
    return temp

    
def newSE_count(run,se,n,j):
    temp = list()
    for k in se[n][np.abs(se[n][:,2] - (run.prune_data[n].fits[j].phase_r-run.prune_data[n].fits[j].phase_l)/np.pi%2)<0.001]:
        temp.append(k)
    return temp


In [ ]:
def plotGrid(run,se,start,fit_list,k,x_low,x_high,colspan,rowspan,xy=(-0.05, 1.02),lw=1.2,linew=2):
    plt.subplot2grid((100,100), start, colspan=colspan, rowspan=rowspan)
    j = fit_list[k][1]
    n = fit_list[k][0]
    run.prune_data[n].plot_fit(j,linewidth=linew)
    axes(run.prune_data[n],j,x_low,x_high)
    for k in se[n][np.abs(se[n][:,2] - (run.prune_data[n].fits[j].phase_r-run.prune_data[n].fits[j].phase_l)/np.pi%2)<0.001]:
        plt.axvline(k[0],color='k',lw=lw)
    plt.annotate('{:.4f} T'.format(run.prune_data[n].b_val), xy, xycoords="axes fraction")
        

def axes(sweep,j,x_min,x_max):
    plt.xlim(x_min,x_max)
    x = np.linspace(x_min,x_max)
    yl,yr = sweep.fits[j].yValue(x)
    y_min = np.min([yl,yr])
    y_max = np.max([yl,yr])
    l,h = t(y_min,y_max)
    plt.ylim(l,h)
    plt.yticks([y_min,y_max],(round(y_min,1),round(y_max,1)))
    x_low, x_high = np.percentile(x,[25,75])
    plt.xticks([int(x_low),int(x_high)])
    ax = plt.gca()
    ax.tick_params('y',pad=2)
    ax.tick_params('x',pad=3)
    
    
def newplotGrid(bounds,colspan,rowspan,xy=(-0.05, 1.02)):
    run,se,fit_list,k,x_low,x_high = bounds
    j = fit_list[k][1]
    n = fit_list[k][0]
    run.prune_data[n].plot_fit(j)
    axes(run.prune_data[n],j,x_low,x_high)
    for k in se[n][np.abs(se[n][:,2] - (run.prune_data[n].fits[j].phase_r-run.prune_data[n].fits[j].phase_l)/np.pi%2)<0.001]:
        plt.axvline(k[0],color='k',lw=2)
    plt.annotate('{} T'.format(run.prune_data[n].b_val), xy, xycoords="axes fraction")


In [ ]:
pi4_14 = [[0,0],[0,2],[0,3],[2,1],[2,2],[3,3],[3,4],[4,1],[5,0],[7,2],[8,0],[8,3],[9,0]]
pi2_14 = [[3,2],[3,1]] 
pi34_14 = [[2,0],[2,3],[3,0],[8,1]]
pi_14 = [[0,1],[4,0],[5,1],[6,0],[7,1],[8,2],[9,1],[10,0],[11,0],[13,0],[13,1]]
pi74_14 = [[5,2]]
#------------------------------------------
pi4_11 = [[0,0],[5,0],[9,1],[11,0],[14,0],[19,1]]
pi2_11 = [[2,1],[4,0],[12,1],[15,0],[19,0]]
pi34_11 = [[0,1],[1,1],[10,0],[13,0]]
pi_11 = [[1,0],[2,0],[3,0],[4,1],[5,1],[6,0],[7,0],[8,0],[9,2],[11,1],[12,0],[14,1],[15,1],[16,0],[17,0],[19,2],[21,0]]
#No pi7/4 for 2011

In [ ]:
pi_11_bounds = [[soft11,se11,pi_11,0,-26.34,-18.02],[run11,se11,pi_11,1,-38.84,-29.39],
                [run11,se11,pi_11,2,-41.13,-29.99],[soft11,se11,pi_11,3,-42.59,-31.06],
                [run11,se11,pi_11,4,-41.27,-30.44],[soft11,se11,pi_11,5,-41,-30],
                [soft11,se11,pi_11,6,-40,-29.82],[run11,se11,pi_11,7,-39.23,-28.47],
                [run11,se11,pi_11,8,-39.9,-29.56],[run11,se11,pi_11,9,-38.2,-29.144],
                [run11,se11,pi_11,10,-42.07,-31.46],[run11,se11,pi_11,11,-41.87,-29.9],
                [run11,se11,pi_11,12,-41.29,-30.3],[run11,se11,pi_11,13,-40.29,-30.86],
                [run11,se11,pi_11,14,-41.36,-32.15],[run11,se11,pi_11,15,-41.33,-31.54],
                [run11,se11,pi_11,16,-40.7672,-30.3]]

pi_14_bounds = [[soft14,se14,pi_14,0,-19.48,-9.83],[soft14,se14,pi_14,1,-18.18,-7.05],
       [run14,se14,pi_14,2,-21.14,-8.78],[run14,se14,pi_14,3,-16.54,-9],
       [soft14,se14,pi_14,4,-17.8,-10.38],[run14,se14,pi_14,5,-15.18,-7.22],
       [soft14,se14,pi_14,6,-17.8,-9.72],[soft14,se14,pi_14,7,-20.02,-9.20],
       [run14,se14,pi_14,8,-20.4,-8.65],[run14,se14,pi_14,9,-19.32,-7.76],
       [run14,se14,pi_14,10,-27.51,-17.93]]

In [ ]:
pi4_14_bounds = [[run14,se14,pi4_14,0,-11,-7],[run14,se14,pi4_14,1,-21,-16],
       [run14,se14,pi4_14,2,-23.67,-19.6],[run14,se14,pi4_14,3,-19.48,-15.83],
       [run14,se14,pi4_14,4,-21,-18.66],[soft14,se14,pi4_14,5,-21.6,-18.4],
       [soft14,se14,pi4_14,6,-27,-20.99],[soft14,se14,pi4_14,7,-23.14,-19.58],
       [run14,se14,pi4_14,8,-14.16,-7.65],[run14,se14,pi4_14,9,-26.29,-19.04],
       [run14,se14,pi4_14,10,-31.0675,-25.2242],[soft14,se14,pi4_14,11,-25.6274,-18.36],
       [run14,se14,pi4_14,12,-25.78,-19.49]]

pi4_11_bounds = [[soft11,se11,pi4_11,0,-31.9,-23.479],[soft11,se11,pi4_11,1,-31.84,-26.8],
       [soft11,se11,pi4_11,2,-32,-14.24],[soft11,se11,pi4_11,3,-31.53,-17.82],
       [soft11,se11,pi4_11,4,-33.6,-24.22],[soft11,se11,pi4_11,5,-33.5,-28]]

In [ ]:
pi_new = list()

pi_bounds = list(pi_11_bounds)
pi_bounds.extend(pi_14_bounds)
pi_bounds = np.array(pi_bounds)


for j in [15,14,13,12,11,8,7,6,5,4,3,2,23,21,20]:
    pi_new.append(pi_bounds[j])

pi_new[0][-2],pi_sup[0][-1] = -42.3122, -30.0638
pi_new[1][-2],pi_new[1][-1] = -42.01,-29.714
pi_new[2][-2],pi_new[2][-1] = -43.739,-30.7454
pi_new[3][-2],pi_new[3][-1] = -45.9674,-30.1864
pi_new[4][-2],pi_new[4][-1] = -42.0237, -29.9358
pi_new[5][-2],pi_new[5][-1] = -41.2647, -29.5113
pi_new[6][-2],pi_new[6][-1] = -40.6632, -28.4236
pi_new[7][-2],pi_new[7][-1] = -40, -29.8989
pi_new[8][-2],pi_new[8][-1] = -45.3157, -29.8903
pi_new[9][-2],pi_new[9][-1] = -43.3091, -30.3461
pi_new[10][-2],pi_new[10][-1] = -42.7017, -31.0218
pi_new[11][-2],pi_new[11][-1] = -41.9687, -29.6581
pi_new[12][-2],pi_new[12][-1] = -19.7687, -7.3317
pi_new[13][-2],pi_new[13][-1] = -21.0172, -9.7475
pi_new[14][-2],pi_new[14][-1] = -17.1242, -5.575

In [ ]:
pi_sup = list()

pi_bounds = list(pi_11_bounds)
pi_bounds.extend(pi_14_bounds)
pi_bounds = np.array(pi_bounds)


for j in [16,10,9,1,27,26,25,24,22,19,18,17]:
    pi_sup.append(pi_bounds[j])


pi_sup[0][-2],pi_sup[0][-1] = -42.9495,-30.1496

pi_sup[1][-2],pi_sup[1][-1] = -46.7153, -30.7536
pi_sup[2][-2],pi_sup[2][-1] = -43.7484, -29.2676
pi_sup[3][-2],pi_sup[3][-1] = -38.8846, -29.3708
pi_sup[4][-2],pi_sup[4][-1] = -27.4837, -17.0424
pi_sup[5][-2],pi_sup[5][-1] = -19.7555, -7.7148
pi_sup[6][-2],pi_sup[6][-1] = -20.5392, -8.4924
pi_sup[7][-2],pi_sup[7][-1] = -20.2131, -8.3886
pi_sup[8][-2],pi_sup[8][-1] = -15.3165, -7.1523
pi_sup[9][-2],pi_sup[9][-1] = -20.9327, -12.2644
pi_sup[10][-2],pi_sup[10][-1] = -20.6114, -7.0573
pi_sup[11][-2],pi_sup[11][-1] = -19.4212, -8.5128
#pi_sup[13][-2],pi_sup[13][-1] = 
#pi_sup[14][-2],pi_sup[14][-1] = 

In [ ]:
pi4_new = list()

pi4_bounds = list(pi4_14_bounds)
pi4_bounds.extend(pi4_11_bounds)
pi4_bounds = np.array(pi4_bounds)


for j in [3,9,6,10,1,0,2,4,5]:
    pi4_new.append(pi4_bounds[j])

pi4_new[1][-2],pi4_new[1][-1] = -28.371,-19.6137
pi4_new[3][-2],pi4_new[3][-1] = -31.0697,-22.9274
pi4_new[4][-2],pi4_new[4][-1] = -22.15,-15.3109
pi4_new[5][-2],pi4_new[5][-1] = -13.4502,-6.9825
pi4_new[6][-2],pi4_new[6][-1] = -28.371,-19.4487

In [ ]:
pi2_bounds = [[soft14,se14,pi2_14,0,-20,-15],[soft14,se14,pi2_14,1,-16.2,-10.3],
                [run11,se11,pi2_11,0,-42.48,-35.65],[soft11,se11,pi2_11,1,-35.46,-25.65],
                [soft11,se11,pi2_11,2,-42.47,-36.3],[soft11,se11,pi2_11,3,-31.59,-23.59],
                [run11,se11,pi2_11,4,-26.74,-19.2]]

pi2_new = list()
for j in [6,3,0,4]:
    pi2_new.append(pi2_bounds[j])
pi2_new[0][-2],pi2_new[0][-1] = -28.79,-18
pi2_new[2][-2],pi2_new[2][-1] = -22.22,-15.429
pi2_new[3][-2],pi2_new[3][-1] = -43.3619,-33.96

In [ ]:
pi34_bounds = [[run14,se14,pi34_14,0,-13.17,-4.05],[soft14,se14,pi34_14,1,-28.02,-21.7],
               [run14,se14,pi34_14,2,-12.9,-4.06],[soft14,se14,pi34_14,3,-12.04,-4.05],
               [run11,se11,pi34_11,0,-41.1,-34.2],[soft11,se11,pi34_11,1,-40.5,-31.7],
               [run11,se11,pi34_11,2,-37.159,-29],[run11,se11,pi34_11,3,-39.48,-30.16],
               [soft11,se11,pi_11,0,-26.4479, -17.6429]]

# $\pi$ Figures

In [ ]:
lw = 1.6 #slip lines
linew = 2.5 #fit lines
xy=(-0.023, 1.02)
height = 4
width = 3
row_extra = 4
row_len = (100-row_extra*(height-1))/height
col_extra = 4
col_len = (100-col_extra*(width-1))/width
fig = plt.figure(figsize = (1.5*2.42/(col_len/100.),1.5/(row_len/100.)))

for i in range(len(pi_new)):
    current = (i/width*(row_extra+row_len),i%width*(col_extra+col_len))
    hold = list(pi_new[-i-1])
    plotGrid(hold[0],hold[1],current,hold[2],hold[3],hold[4],hold[5],col_len,row_len,xy=xy,lw=lw,linew=linew)
    if i == 6:
        plt.ylabel('$R_D(k\Omega)$',labelpad=4,size=18)
        #ax = plt.gca()
        #ax.yaxis.set_label_coords(-.17,1.1)
    if i == 13:
        plt.xlabel('$V_P(mV)$',labelpad=4,size=18)    

In [ ]:
fig.savefig('Pi Main Fig 6_2019',dpi=1000)

In [ ]:
lw = 1.6 #slip lines
linew = 2.5 #fit lines
xy=(-0.023, 1.02)
height = 4
width = 3
row_extra = 6
row_len = (100-row_extra*(height-1))/height
col_extra = 4
col_len = (100-col_extra*(width-1))/width
fig = plt.figure(figsize = (1.5*2.42/(col_len/100.),1.5/(row_len/100.)))
out = list()
for i in range(len(pi_sup)-1):
    current = (i/width*(row_extra+row_len),i%width*(col_extra+col_len))
    hold = list(pi_sup[-i-2])
    if i >= len(pi_sup)-3:
            current = (i/width*(row_extra+row_len),i%width*(col_extra+col_len)+int((col_extra+col_len)/2))
    plotGrid(hold[0],hold[1],current,hold[2],hold[3],hold[4],hold[5],col_len,row_len,xy=xy,lw=lw,linew=linew)
    out.append(newSE_count(hold[0],hold[1],hold[2][hold[3]][0],hold[2][hold[3]][1]))
    if i == 6:
        plt.ylabel('$R_D$$(k\Omega)$',labelpad=4,size=18)
        ax = plt.gca()
        ax.yaxis.set_label_coords(-.17,1.1)
    if i == 10:
        plt.xlabel('$V_P$$(mV)$',labelpad=4,size=18)
        ax = plt.gca()
        ax.xaxis.set_label_coords(-0.06,-0.25)
      

In [ ]:
fig.savefig('Pi Sup Fig 6_2019',dpi=1000)

# $\pi/4$ Figure

In [ ]:
#Version 22
#Now has extended sweep on bottom
#Rest same as 18
mpl.rcParams.update({'font.size': 11})
xy=(-0.023, 1.02)
lw = 2.0 #slip lines
linew = 2.5 #fit lines
height = 3
width = 2
row_extra = 8
row_len = (100-row_extra*(height-1))/height
col_extra = 7
col_len = (100-col_extra*(width-1))/width
fig = plt.figure(figsize = (1.5*2.42/(col_len/100.),1.5/(row_len/100.)))
i = 0
o = 5
out = list()
for j in [3,1,0,2,4,5]:
    hold = pi4_new[j]
    current = (o/width*(row_extra+row_len),o%width*(col_extra+col_len))
    o -= 1

    
    if i == 2:
        plt.subplot2grid((100,100), current, colspan=col_len, rowspan=row_len)
        n = 3
        j = 3
        init_plot(i14[n])
        i14[n].fits[4].plot_select('l','#663300',linew,-26.8855,-21.1362)

        i14[n].fits[4].plot_select('r','k',linew,-26.8855,-21.615)
        i14[n].fits[3].plot_select('l','k',linew,-21.615,-19.0156)

        i14[n].fits[3].plot_select('r','r',linew,-22.5746,-19.0156)

        set_axis(i14[n],-26.8855,-19.0156)
        plt.xticks([-25,-20])

        plt.axvline(-20.2475,color='k',lw=lw)
        for k in se14[n][np.abs(se14[n][:,2] -  (2-i14[n].fits[4].delta_phi))<0.01]:
            plt.axvline(k[0],color='k',lw=lw)
        
        temp = newSE_count(run14,se14,3,3)
        temp.append(newSE_count(run14,se14,3,4)[0])
        out.append(temp)

        
        plt.annotate('{:.4f} T'.format(i14[n].b_val), xy, xycoords="axes fraction")
        
        i+=1
        continue
    
    if i == 3:
        plt.subplot2grid((100,100), current, colspan=col_len, rowspan=row_len)
        n = 2
        j = 2
        init_plot(i14[n])
        i14[n].fits[2].plot_select('l','#663300',linew,-21.6517,-19.2432)

        i14[n].fits[2].plot_select('r','k',linew,-21.6517,-17.8369)
        i14[n].fits[1].plot_select('l','k',linew,-17.8369,-14.6178)
        
        i14[n].fits[1].plot_select('r','r',linew,-19.839,-14.6178)
        set_axis(i14[n],-21.6517,-14.6178)
        
        #As the fits are all very close in delta_phi, this captures both fits
        for k in se14[n][np.abs(se14[n][:,2] -  (2-i14[n].fits[2].delta_phi))<0.01]:
            plt.axvline(k[0],color='k',lw=lw)
        
        temp = newSE_count(run14,se14,2,2)
        temp.extend(newSE_count(run14,se14,2,1))
        out.append(temp)
        
        plt.xticks([-20,-15])
        
        plt.annotate('{:.4f} T'.format(i14[n].b_val), xy, xycoords="axes fraction")
        
        plt.ylabel('$R_D(k\Omega)$',labelpad=3,size=18)
        
        i += 1
        continue
    
    
    if i == 4:
        current = (0,0)
        plt.subplot2grid((100,100), current, colspan=2*col_len+col_extra, rowspan=row_len)
        n = 0
        j = 2

        lw = 2.0 #slip lines
        linew = 2.5 #fit lines

        init_plot(soft14.prune_data[n]) #v1
        #plt.plot(d140[0],d140[1]) #v2

        i14[n].fits[3].plot_select('l','k',linew,-25.8592,-20.75)      
        i14[n].fits[3].plot_select('r','r',linew,-25.8592,-20.75)

        i14[n].fits[3].plot_select('r','k',linew,-20.4608,-19.8804)
        i14[n].fits[2].plot_select('l','k',linew,-19.8804,-17.2498)
        i14[n].fits[2].plot_select('r','r',linew,-20.4608,-18.675)
        i14[n].fits[1].plot_select('l','r',linew,-18.675,-17.2498)
        
        
        i14[n].fits[1].plot_select('l','k',linew,-16.8737,-11.0015)
        i14[n].fits[1].plot_select('r','r',linew,-16.8737,-11.0015)


        i14[n].fits[0].plot_select('l','k',linew,-10.5675,-6.98202)
        i14[n].fits[0].plot_select('r','r',linew,-10.5675,-6.98202)

        for k in se14[n]:
            plt.axvline(k[0],color='k',lw=lw)

        set_axis(i14[n],-26.0964,-6.98202)
        
        plt.annotate('{:.4f} T'.format(i14[0].b_val),(-0.01, 1.02), xycoords="axes fraction")
        
        
        
        temp = [se14[0][0]]
        temp.extend(newSE_count(run14,se14,0,1))
        temp.extend(newSE_count(run14,se14,0,2))
        temp.extend(newSE_count(run14,se14,0,3))
        out.append(temp)
        
        plt.xticks([-25,-20,-15,-10])
        break
    
    
    plotGrid(hold[0],hold[1],current,hold[2],hold[3],hold[4],hold[5],col_len,row_len,xy=(-0.023, 1.02),lw=lw,linew=linew)
    
    #Add extra lines for the nonplotted fit
    if i == 0:
        n = 8
        j = 3
        for k in se14[n][np.abs(se14[n][:,2] -  (2-i14[n].fits[j].delta_phi))<0.01]:
            plt.axvline(k[0],color='k',lw=lw)
        temp = newSE_count(run14,se14,8,0)
        temp.extend(newSE_count(run14,se14,8,3)[0:2])
        out.append(temp)
        i += 1
        plt.xticks([-30,-25])
        plt.xlabel('$V_P(mV)$',labelpad=4,size=18)
        ax = plt.gca()
        ax.xaxis.set_label_coords(-0.07,-0.22)
        continue
           
    if i == 1:
        plt.xticks([-25,-20])
        
    out.append(newSE(*hold)) 
    i += 1


In [ ]:
fig.savefig('025Pi Fig 6_2019',dpi=1000)

# $\pi/2$ Figure

In [ ]:
xy=(-0.023, 1.02)
lw = 2.0 #slip lines
linew = 2.5 #fit lines
height = 1
width = 2
row_extra = 9
bot = 16
row_len = (100-row_extra*(height-1)-bot)/height
col_extra = 10
col_len = (100-col_extra*(width-1))/width

fig = plt.figure(figsize = (1.5*2.42/(col_len/100.),1.5/(row_len/100.)))
i = 0
out = list()
for j in range(2):
    hold = pi2_new[(j+1)%2]
    
    current = (i/width*(row_extra+row_len),i%width*(col_extra+col_len))
    plotGrid(hold[0],hold[1],current,hold[2],hold[3],hold[4],hold[5],col_len,row_len,xy=xy,lw=lw,linew=linew)
    
    if i == 0:
        plt.ylabel('$R_D(k\Omega)$',labelpad=0,size=18)
    if i == 1:
        plt.xlabel('$V_P(mV)$',labelpad=0,size=18)
        ax = plt.gca()
        ax.xaxis.set_label_coords(-0.1,-0.17)
    out.append(newSE(*hold)) 
    i += 1


In [ ]:
fig.savefig('05Pi Fig 6_2019',dpi=1000)

# 3$\pi$/4 Figure

In [ ]:
xy=(-0.023, 1.02)
lw = 2.0 #slip lines
linew = 2.5 #fit lines
height = 3
width = 3
row_extra = 8
bot = 3
row_len = (100-row_extra*(height-1)-bot)/height
col_extra = 4
col_len = (100-col_extra*(width-1))/width
fig = plt.figure(figsize = (1.5*2.42/(col_len/100.),1.5/(row_len/100.)))
i = 0
out = list()
for j in [0,2,4,5,-1,6,7]:
    hold = pi34_bounds[j]
    current = (i/width*(row_extra+row_len),i%width*(col_extra+col_len))
    if i == 6:
        current = (i/width*(row_extra+row_len),(i+1)%width*(col_extra+col_len))
    plotGrid(hold[0],hold[1],current,hold[2],hold[3],hold[4],hold[5],col_len,row_len,xy=xy,lw=lw,linew=linew)
    if i == 3:
        plt.ylabel('$R_D(k\Omega)$',labelpad=0,size=18)
        ax = plt.gca()
        ax.yaxis.set_label_coords(-0.15,1.12)
    if i == 6:
        plt.xlabel('$V_P(mV)$',labelpad=5,size=18)
    #out.append(newSE(*hold))    
    i += 1

In [ ]:
fig.savefig('075Pi Fig 6_2019',dpi=1000)

# Color Maps

In [8]:
data2011 = np.load('2011_Prune_strong_flat.npy')
data2014 = np.load('2014_Prune_strong.npy')

d2011 = list()
for i in range(len(data2011)):
    d2011.append(np.array([tuple(j) for j in data2011[i]],dtype=np.float))

d2014 = list()
for i in range(len(data2014)):
    d2014.append(np.array([tuple(j) for j in data2014[i]],dtype=np.float))

In [9]:
import SG
import pylab
from scipy import interpolate

In [10]:
cdict = {'red':   ((0.0, 0.0, 0.0),
                   (0.5, 1.0, 1.0),
                   (1.0, 1.0, 1.0)),

         'green': ((0.0, 0.0, 0.0),
                   (0.5,0.0,0.0),
                   (1.0, 1.0, 1.0)),

         'blue':  ((0.0, 1.0, 1.0),
                   (0.5, 0.0, 0.0),
                   (1.0, 0.0, 0.0))
        }
        
yellowredblue = LinearSegmentedColormap('YellowRedBlue', cdict)

In [11]:
def percentile_normalize(data,p=1):
    minv = np.percentile(data,p)
    maxv = np.percentile(data,100-p)
    hold = np.array(data)
    for i in range(len(hold)):
        hold[i] = (hold[i]-minv)/(maxv-minv)
    return hold

In [12]:
def search(data, t):
    seq = data[0]    
    min = 0
    max = len(seq) - 1
    while True:        
        m = (min + max) // 2
        if max < min:
            if np.abs(t-seq[m]) < np.abs(t-seq[m-1]):          
                return m
            else:
                return m-1        
        if seq[m] < t:
            min = m + 1
        elif seq[m] > t:
            max = m - 1
        else:
            return m
            

def clip(d,min,max):
    data = np.array(d)
    li = search(data,min)
    ri = search(data,max)
    return data[:,li:ri+1]
    

In [13]:
def normalize(data):
    minv = min(data)
    maxv = max(data)
    hold = np.array(data)
    for i in range(len(hold)):
        hold[i] = (hold[i]-minv)/(maxv-minv)
    return hold

In [14]:
from matplotlib.gridspec import GridSpec
gs = GridSpec(1000,1000)


## 2014 Data

In [141]:
#More smoothing, better option
bfieldval = Analysis.bval2014
n = 1024
smoothval = 51
poly = 2
interpdim = 2
data = d2014
cmlabel = 'Normalized $\Delta$R$_D$ (k$\Omega$)'
data = [x for (y,x) in sorted(zip(bfieldval,data), key=lambda pair: pair[0])]
bval = sorted(bfieldval)    
xmin = -100
xmax = 0
for i in data:
    if i[0][0] > xmin:
        xmin = i[0][0]
    if i[0][-1] < xmax:
        xmax = i[0][-1]
#xmin += 0.01
#xmax -= 0.01
xv = np.linspace(xmin,xmax,n)
intv = list()
for i in data:
    #Try flipping filtering and interp
    dataclip = clip(i,xmin,xmax)
    dataclip[1] = SG.savitzky_golay(dataclip[1],smoothval,poly)
    tck = interpolate.splrep(dataclip[0], dataclip[1],k=1)
    y = interpolate.splev(xv,tck)
    intv.append(percentile_normalize(y,1))
xb = np.linspace(bval[0],bval[-1],n)
b = list()
for i in range(len(intv[0])):
    hold = list()
    for j in range(len(intv)):
        hold.append(intv[j][i])
    b.append(hold)
intb = list()
for i in b:
    tck = interpolate.splrep(bval,i,k=interpdim)
    y = interpolate.splev(xb,tck)
    intb.append(y)
Z = np.array(intb)
X,Y = pylab.meshgrid(xb,xv)

In [46]:
colortype = yellowredblue
f, ax = plt.subplots()
plt.pcolormesh(X,Y,Z,vmin=0,vmax=1,cmap=colortype)
plt.ylim(xmin,xmax)
plt.xlim(bval[0],bval[-1])
plt.ylabel('Gate Voltage(mV)',size=18)
plt.xlabel('B Field(T)',size=18)
cbar = plt.colorbar()
cbar.set_label(cmlabel,size=14)
ax.get_xaxis().get_major_formatter().set_useOffset(False)

plt.show()

In [73]:
Y[360][0]

-21.505043665689151

In [74]:
i = 360
plt.figure()
plt.plot(X[i],Z[i])

In [ ]:
f.savefig('Color Map 14 2019',dpi=1200)

In [142]:
f, ax = plt.subplots()
plt.pcolormesh(X,Y,Z,vmin=0,vmax=1,cmap='binary')
plt.ylim(xmin,xmax)
plt.xlim(bval[0],bval[-1])
plt.ylabel('$V_P$(mV)',size=18)
plt.xlabel('B(T)',size=18)
plt.yticks([-30,-20,-10])
plt.xticks([5.578,5.580,5.582,5.584])
cbar = plt.colorbar(ticks=[0.0,1.0],shrink=0.5)
cbar.set_label('$\Delta$R$_D$ (k$\Omega$)',size=14)
ax.get_xaxis().get_major_formatter().set_useOffset(False)

plt.show()

In [143]:
#Markers with +/- signs
shift = 0.00008

for i in sw34m:
    if i[1]>Analysis.bval2011[0]:
        x = float(i[1])
        if x==5.5845:
            x -= shift
        if i[2] > 0:
            q34 = plt.scatter(x,i[0],s=50,color='#FFD700',marker='v',edgecolor='k',linewidth='1',label='$\Delta\\theta=3\pi/4')
        else:
            qm34 = plt.scatter(x,i[0],s=50,color='#CD853F',marker='v',edgecolor='k',linewidth='1',label='$\Delta\\theta=-3\pi/4')


for i in sw14m:
    if i[1]>Analysis.bval2011[0]:
        x = float(i[1])
        if x==5.5845:
            x -= shift
        if i[2] > 0:
            q = plt.scatter(x,i[0],s=50,color='#0000FF',marker='D',edgecolor='k',linewidth='1',label='$\Delta\\theta=\pi/4')
        else:
            qm = plt.scatter(x,i[0],s=50,color='#87CEFA',marker='D',edgecolor='k',linewidth='1',label='$\Delta\\theta=-\pi/4')

for i in pim:    
    if i[1]>Analysis.bval2011[0]:
        x = float(i[1])
        if x==5.5845:
            x -= shift
        if i[2] > 0:
            p = plt.scatter(x,i[0],s=50,color='r',edgecolor='k',linewidth='1',label='$\Delta\\theta=\pi')
        else:
            pm = plt.scatter(x,i[0],s=50,color='orange',edgecolor='k',linewidth='1',label='$\Delta\\theta=-\pi')

#plt.legend([q,qm,q34,p,pm], ["$\Delta\\theta =\pi/4$","$\Delta\\theta =-\pi/4$","$\Delta\\theta =3\pi/4$","$\Delta\\theta =\pi$","$\Delta\\theta =-\pi$"],ncol = 2,loc=2,scatterpoints=1)

In [144]:
f.savefig('Grayscale Color Map 14 2019 v3',dpi=1000)

# 2011 Data

In [15]:
bfieldval = Analysis.bval2011
n = 1024
smoothval = 51
poly = 2
interpdim = 2
data = d2011
cmlabel = 'Normalized $\Delta$R$_D$ (k$\Omega$)'
data = [x for (y,x) in sorted(zip(bfieldval,data), key=lambda pair: pair[0])]
bval = sorted(bfieldval)    
xmin = None
xmax = 0
for i in data:
    if i[0][0] > xmin:
        xmin = i[0][0]
    if i[0][-1] < xmax:
        xmax = i[0][-1]
xmin += 0.5
xmax -= 0.5
xv = np.linspace(xmin,xmax,n)
intv = list()
count = 0
for i in data:
    if count == 21:
        xmin += 1
    #Try flipping filtering and interp
    dataclip = clip(i,xmin,xmax)
    dataclip[1] = SG.savitzky_golay(dataclip[1],smoothval,poly)
    tck = interpolate.splrep(dataclip[0], dataclip[1],k=1)
    y = interpolate.splev(xv,tck)
    intv.append(percentile_normalize(y,1))
    count += 1
xb = np.linspace(bval[0],bval[-1],n)
b = list()
for i in range(len(intv[0])):
    hold = list()
    for j in range(len(intv)):
        hold.append(intv[j][i])
    b.append(hold)
intb = list()
for i in b:
    tck = interpolate.splrep(bval,i,k=interpdim)
    y = interpolate.splev(xb,tck)
    intb.append(y)
Z = np.array(intb)
X,Y = pylab.meshgrid(xb,xv)


In [42]:
colortype = yellowredblue
f, ax = plt.subplots()
plt.pcolormesh(X,Y,Z,vmin=0,vmax=1,cmap=colortype)
plt.ylim(xmin,xmax)
plt.xlim(bval[0],bval[-1])
plt.ylabel('Gate Voltage(mV)',size=18)
plt.xlabel('B Field(T)',size=18)
cbar = plt.colorbar()
cbar.set_label(cmlabel,size=14)
ax.get_xaxis().get_major_formatter().set_useOffset(False)

plt.show()

In [27]:
Y[358][0]

-32.767286211143691

In [28]:
i = 358
plt.figure()
plt.plot(X[i],Z[i])

In [ ]:
f.savefig('Color Map 11 2019',dpi=1200)

In [138]:
f, ax = plt.subplots()
plt.pcolormesh(X,Y,Z,vmin=0,vmax=1,cmap='binary')
plt.ylim(xmin,xmax)
plt.xlim(bval[0],bval[-1])
plt.ylabel('$V_P$(mV)',size=18)
plt.xlabel('B(T)',size=18)
plt.yticks([-40,-30,-20,-10])
plt.xticks([5.526,5.530,5.534])
cbar = plt.colorbar(ticks=[0.0,1.0],shrink=0.5)
cbar.set_label('$\Delta$R$_D$ (k$\Omega$)',size=14)
ax.get_xaxis().get_major_formatter().set_useOffset(False)

plt.show()

In [ ]:
#Has Vertical Scale
xin = 5
yin = 5
img = xin*0.9
y_len = int(img/yin*1000)
colortype = ch.yellowredblue
f= plt.figure(figsize=[xin,1.06*xin])
ax = f.add_subplot(gs[100:y_len,100:])
im = ax.pcolormesh(X,Y,Z,vmin=0,vmax=1,cmap='binary')
ax.get_xaxis().get_major_formatter().set_useOffset(False)
plt.xticks([5.526,5.530,5.534])
plt.yticks([-40,-30,-20,-10])
ax.set_ylim(xmin,xmax)
ax.set_xlim(bval[0],bval[-1])
plt.ylabel('V$_{p}$(mV)',labelpad=-1)
plt.xlabel('B(T)')
cax = f.add_subplot(gs[65:90,400:700])

cbar = plt.colorbar(im,cax=cax,ticks=[0.0,0.5,1.0],orientation='horizontal')
cax.xaxis.set_label_position('top')
cax.set_xlabel('$\Delta$R$_D$ (k$\Omega$)')
cax.xaxis.labelpad = 2
cax.tick_params(axis='x',which='both',bottom='off',top='on',labelbottom='off',labeltop='on',labelsize=8,pad=0)

In [139]:
#Markers PM
#for i in new14:
#    if i[1]<=bval2011[0]:
#        q = plt.scatter(i[1],i[0],s=60,color='#00FFFF',marker='d',edgecolor='k',linewidth='1',label='$\Delta\phi=\pi/4')
shift = 0.00008
for i in pim:
    if i[1]<=Analysis.bval2011[0]:
        if i[2] > 0:
            p = plt.scatter(i[1],i[0],s=50,color='r',edgecolor='k',linewidth='1',label='$\Delta\theta=\pi')
        else:
            pm = plt.scatter(i[1],i[0],s=50,color='orange',edgecolor='k',linewidth='1',label='$\Delta\theta=-\pi')
for i in sw34m:
    if i[1]<=Analysis.bval2011[0]:
        x = float(i[1])
        if x==5.536:
            x -= shift
        if i[2] > 0:
            q34 = plt.scatter(x,i[0],s=50,color='#FFD700',marker='v',edgecolor='k',linewidth='1',label='$\Delta\\theta=3\pi/4')
        else:
            qm34 = plt.scatter(x,i[0],s=50,color='#CD853F',marker='v',edgecolor='k',linewidth='1',label='$\Delta\\theta=-3\pi/4')
            
for i in sw12m:
    if i[1]<=Analysis.bval2011[0]:
        x = float(i[1])
        if x==5.536:
            x -= shift
        if i[2] > 0:
            q05 = plt.scatter(x,i[0],s=50,color='#006400',marker='s',edgecolor='k',linewidth='1',label='$\Delta\\theta=\pi/2')
        else:
            qm05 = plt.scatter(x,i[0],s=50,color='#00FF00',marker='s',edgecolor='k',linewidth='1',label='$\Delta\\theta=-\pi/2')
            
plt.legend([q,qm,q05,qm05,q34,qm34,p,pm], ["$\Delta\\theta =\pi/4$","$\Delta\\theta =-\pi/4$","$\Delta\\theta =\pi/2$","$\Delta\\theta =-\pi/2$","$\Delta\\theta =3\pi/4$","$\Delta\\theta =-3\pi/4$","$\Delta\\theta =\pi$","$\Delta\\theta =-\pi$"],
           loc=2,scatterpoints=1,ncol=2,fontsize='small',columnspacing=0,labelspacing=0.5,handletextpad=0)


In [140]:
f.savefig('Grayscale Color Map 11 2019 v3',dpi=1000)

# Computing Periods

In [119]:
temp = list()

for i in prunedfig:
    for j in i:
        temp.append(j[2])
for i in prunedsup:
    for j in i:
        temp.append(j[2])


In [120]:
freq_hold11 = list()
freq_hold14 = list()
for i in i11:
    for j in i.fits:
        if (j.phase_r-j.phase_l)/np.pi%2 in temp:
            freq_hold11.append(1/(j.freq/(2*np.pi)))
for i in i14:
    for j in i.fits:
        if (j.phase_r-j.phase_l)/np.pi%2 in temp:
            freq_hold14.append(1/(j.freq/(2*np.pi)))

In [123]:
len(freq_hold14)

10

In [121]:
plt.hist(freq_hold11)

(array([ 1.,  0.,  1.,  3.,  4.,  2.,  3.,  1.,  0.,  1.]),
 array([ 8.20645897,  8.37958154,  8.55270411,  8.72582668,  8.89894926,
         9.07207183,  9.2451944 ,  9.41831697,  9.59143954,  9.76456211,
         9.93768468]),
 <a list of 10 Patch objects>)

In [124]:
print('2011 Mean = {} with std {}'.format(np.mean(freq_hold11),np.std(freq_hold11)))

2011 Mean = 9.06346594649 with std 0.39560516482


In [125]:
print('2014 Mean = {} with std {}'.format(np.mean(freq_hold14),np.std(freq_hold14)))

2014 Mean = 9.03031742225 with std 0.605220952885


In [126]:
freq_hold025pi = list()

temp025pi = list()

for i in pruned14:
    for j in i:
        temp025pi.append(j[2])

for i in i14:
    for j in i.fits:
        if (j.phase_r-j.phase_l)/np.pi%2 in temp025pi:
            freq_hold025pi.append(1/(j.freq/(2*np.pi)))
            
print('2014 Mean = {} with std {}'.format(np.mean(freq_hold025pi),np.std(freq_hold025pi)))

2014 Mean = 8.22272829423 with std 0.248263808907


In [129]:
freq_hold025pi

[8.3461755722123971,
 8.508331801476487,
 8.508331801476487,
 8.4064294486416582,
 7.8539816339744828,
 8.2950375480788647,
 7.8553423459662204,
 8.2627765823206065,
 7.9681479139207143]

In [151]:
delta = list()
temp = pi[0][2]
hold = pi[0][0]
for i in pi[1:]:
    if i[2] == temp:
        d = round(i[0] - hold,4)
        if d < 5:
            delta.append(d)
        hold = i[0]
    else:
        temp = i[2]
        hold = i[0]

In [152]:
delta

[0.221,
 0.3932,
 2.0079,
 0.1581,
 0.8892,
 0.2377,
 0.1728,
 1.2393,
 0.363,
 1.5609,
 0.213,
 0.1709,
 4.7231,
 0.5218,
 0.3555,
 3.7248,
 0.4054,
 0.1681,
 0.848,
 0.7451,
 0.5957,
 0.2027,
 0.7379,
 0.915,
 0.2637]

In [148]:
pi

array([[-14.4746    ,   5.5825    ,   1.02110047,   1.        ],
       [ -7.651     ,   5.5825    ,   1.02110047,   1.        ],
       [ -7.43      ,   5.5825    ,   1.02110047,   1.        ],
       [-14.2383    ,   5.582     ,   0.99611736,   1.        ],
       [-13.8221    ,   5.5805    ,   0.9816624 ,   1.        ],
       [-13.9362    ,   5.5795    ,   0.95692798,   1.        ],
       [-13.7099    ,   5.579     ,   0.94285897,   1.        ],
       [-15.348325  ,   5.578     ,   0.91429435,   1.        ],
       [-14.955145  ,   5.578     ,   0.91429435,   1.        ],
       [-12.94725   ,   5.578     ,   0.91429435,   1.        ],
       [-21.7499    ,   5.578     ,   0.94609601,   1.        ],
       [-35.588805  ,   5.535     ,   0.94226665,   0.83892617],
       [-35.00868   ,   5.5305    ,   0.91014898,   0.89013453],
       [-34.85053   ,   5.5305    ,   0.91014898,   0.89013453],
       [-33.961335  ,   5.5305    ,   0.91014898,   0.89013453],
       [-33.723595  ,   5

In [163]:
plt.hist(delta,bins=30)

(array([ 9.,  4.,  2.,  2.,  3.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
         0.,  0.,  0.,  1.]),
 array([ 0.1581    ,  0.31026667,  0.46243333,  0.6146    ,  0.76676667,
         0.91893333,  1.0711    ,  1.22326667,  1.37543333,  1.5276    ,
         1.67976667,  1.83193333,  1.9841    ,  2.13626667,  2.28843333,
         2.4406    ,  2.59276667,  2.74493333,  2.8971    ,  3.04926667,
         3.20143333,  3.3536    ,  3.50576667,  3.65793333,  3.8101    ,
         3.96226667,  4.11443333,  4.2666    ,  4.41876667,  4.57093333,
         4.7231    ]),
 <a list of 30 Patch objects>)

In [164]:
plt.xlabel('$\Delta$V$_P$(mV)',size=18)

In [165]:
plt.ylabel('Count',size=18)

In [167]:
plt.savefig('Pi Flip Voltage Distribution',dpi=900)

In [166]:
plt.ylim(0,10)

(0, 10)

In [188]:
out = plt.hist(delta,bins=30)

In [170]:
out

(array([ 2.36582694,  1.05147864,  0.52573932,  0.52573932,  0.78860898,
         0.        ,  0.        ,  0.26286966,  0.        ,  0.26286966,
         0.        ,  0.        ,  0.26286966,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.26286966,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.26286966]),
 array([ 0.1581    ,  0.31026667,  0.46243333,  0.6146    ,  0.76676667,
         0.91893333,  1.0711    ,  1.22326667,  1.37543333,  1.5276    ,
         1.67976667,  1.83193333,  1.9841    ,  2.13626667,  2.28843333,
         2.4406    ,  2.59276667,  2.74493333,  2.8971    ,  3.04926667,
         3.20143333,  3.3536    ,  3.50576667,  3.65793333,  3.8101    ,
         3.96226667,  4.11443333,  4.2666    ,  4.41876667,  4.57093333,
         4.7231    ]),
 <a list of 30 Patch objects>)

In [171]:
sum(out[0])

6.571741511500548

In [172]:
len(delta)

25

In [175]:
10.0/25

0.4

In [245]:
plt.bar(out[1][:-1],out[0]/25.0,width=out[1][1]-out[1][0])

<Container object of 30 artists>

In [194]:
x = list()
for i in range(len(out[1])-1):
    x.append((out[1][i+1]+out[1][i])/2)

In [229]:
plt.plot(x,out[0]/25.0)

In [197]:
from scipy.optimize import curve_fit

In [212]:
def func(x,a,r,c):
    return a*np.exp(-(r*x)) + c

In [213]:
popt, pcov = curve_fit(func, x, out[0]/25.0)

In [246]:
plt.plot(np.array(x), func(np.array(x), *popt),'r-',label='fit: a=%5.3f, b=%5.3f, c=%5.3f' % tuple(popt))

In [209]:
func(np.array(x), *popt)

array([-0.06944579,  0.00029206,  0.05314832,  0.0919658 ,  0.11916912,
        0.13682195,  0.14667686,  0.15021848,  0.14870106,  0.14318095,
        0.13454483,  0.12353403,  0.11076571,  0.09675102,  0.08191088,
        0.0665895 ,  0.05106613,  0.03556507,  0.02026431,  0.00530293,
       -0.00921251, -0.02320259, -0.03661038, -0.0493975 , -0.06154074,
       -0.07302926, -0.08386214, -0.09404639, -0.10359519, -0.11252653])

In [247]:
plt.xlabel('$\Delta$V$_P$(mV)',size=18)
plt.ylabel('Probability of Event',size=18)
plt.legend()

In [248]:
plt.text(2.4, 0.3, 'Fitting a*exp(-b*x)+c', fontsize=12)
plt.text(2.4, 0.24, 'Time Constant: {}mV$^-$$^1$'.format(round(1.0/popt[1],3), fontsize=12))

In [237]:
popt

array([ 0.87426956,  4.08270065,  0.00912477])

In [238]:
1.0/popt[1]

0.24493591015818025

In [249]:
plt.savefig('Multi Phase Slip Events with Fit',dpi=900)