In [1]:
import Analysis
import numpy as np
import matplotlib as mpl
from matplotlib import pyplot as plt
from matplotlib.gridspec import GridSpec
import regression_cv as rcv

import FitRoutine2 as fr

In [6]:
%matplotlib

Using matplotlib backend: TkAgg


In [2]:
def csf(scipy_fit):
    x = scipy_fit['result'].x
    out = list()
    out.append(x[2])
    out.append(x[1])
    out.append(x[3]+x[4]*np.pi)
    out.append(x[3])
    out.append(x[0])
    out.append(x[5])
    out.append(scipy_fit['val_acc'])
    out.append(scipy_fit['x_min'])
    out.append(scipy_fit['x_max'])
    phi = x[4]
    out.append(phi)
    out.append(scipy_fit['ci_deltaphi'])
    out.append((scipy_fit['x_min'] + scipy_fit['x_max'])/2)
    return np.array(out)

In [3]:
def search(seq, t):  
    min = 0
    max = len(seq) - 1
    while True:        
        m = (min + max) // 2
        if max <= min:
            if np.abs(t-seq[m]) < np.abs(t-seq[m-1]):          
                return m
            else:
                return m-1        
        if seq[m] < t:
            min = m + 1
        elif seq[m] > t:
            max = m - 1
        else:
            return m


def plot(data,result,full=False,if_data=True):
    x_min = result['x_min']
    x_max = result['x_max']
    if full:
        x = data.x
        y = data.y
    else:
        i_min = search(data.x,x_min)
        i_max = search(data.x,x_max)+1

        x = data.x[i_min:i_max]
        y = data.y[i_min:i_max]

    v0 = (x_min+x_max)/2.0

    params = result['result'].x
    model_l = params[0] + params[1] * np.sin(x*params[2] + (params[3]+params[4]*np.pi)) + params[5] * (x - v0)
    model_r = params[0] + params[1] * np.sin(x*params[2] + params[3]) + params[5] * (x - v0)
    if if_data:
        plt.plot(x,y)
    plt.plot(x,model_r,c='r')
    plt.plot(x,model_l,c='k')

In [4]:
run = Analysis.Run(np.load('73_Raw.npy'), np.load('73_Prune_new.npy'), Analysis.bval73, np.load('73bf_new.npy'))

In [17]:
run.prune_data[filenum].plot()
for i in run.prune_data[filenum].fits:
    i.plot(False)

In [18]:
run_new_rand_d45 = rcv.run_regression(run.prune_data, rcv.regression_CV, d = 3, residual = rcv.residual_new, c = 50, eps = 0.01, x_scale = [10.0,0.1,0.1,1.0,1.0,10**-3], loss = 'huber', y_tol=0.02)
np.save('73_CV_new_res_d3.npy',run_new_rand_d45)

Running sweep 0
Running sweep 1
Running sweep 2
Running sweep 3
Running sweep 4
Running sweep 5
Running sweep 6
Running sweep 7
Running sweep 8
Running sweep 9
Running sweep 10
Running sweep 11
Running sweep 12
Running sweep 13
Running sweep 14
Running sweep 15
Running sweep 16


In [19]:
run_new_rand_d5 = rcv.run_regression(run.prune_data, rcv.regression_CV, d = 4, residual = rcv.residual_new, c = 50, eps = 0.01, x_scale = [10.0,0.1,0.1,1.0,1.0,10**-3], loss = 'huber', y_tol=0.02)
np.save('73_CV_new_res_d4.npy',run_new_rand_d5)

Running sweep 0
Running sweep 1
Running sweep 2
Running sweep 3
Running sweep 4
Running sweep 5
Running sweep 6
Running sweep 7
Running sweep 8
Running sweep 9
Running sweep 10
Running sweep 11
Running sweep 12
Running sweep 13
Running sweep 14
Running sweep 15
Running sweep 16


In [20]:
run_new_rand_d6 = rcv.run_regression(run.prune_data, rcv.regression_CV, d = 5, residual = rcv.residual_new, c = 50, eps = 0.01, x_scale = [10.0,0.1,0.1,1.0,1.0,10**-3], loss = 'huber', y_tol=0.02)
np.save('73_CV_new_res_d5.npy',run_new_rand_d6)

Running sweep 0
Running sweep 1
Running sweep 2
Running sweep 3
Running sweep 4
Running sweep 5
Running sweep 6
Running sweep 7
Running sweep 8
Running sweep 9
Running sweep 10
Running sweep 11
Running sweep 12
Running sweep 13
Running sweep 14
Running sweep 15
Running sweep 16


In [21]:
run_new_rand_d7 = rcv.run_regression(run.prune_data, rcv.regression_CV, d = 6, residual = rcv.residual_new, c = 50, eps = 0.01, x_scale = [10.0,0.1,0.1,1.0,1.0,10**-3], loss = 'huber',y_tol=0.02)
np.save('73_CV_new_res_d6.npy',run_new_rand_d7)

Running sweep 0
Running sweep 1
Running sweep 2
Running sweep 3
Running sweep 4
Running sweep 5
Running sweep 6
Running sweep 7
Running sweep 8
Running sweep 9
Running sweep 10
Running sweep 11
Running sweep 12
Running sweep 13
Running sweep 14
Running sweep 15
Running sweep 16


In [359]:
filenum = 11
val_acc = 0.65
ci_deltaphi = 0.01

In [379]:
for i in run.prune_data[filenum].fits:
    plt.figure()
    run.prune_data[filenum].plot()
    i.plot(False)
    plt.title(i.delta_phi)

In [577]:
t = run_new_rand_d7[filenum]
count = 0
for i in t:
    if i['val_acc']>val_acc and 0.16 < i['result'].x[4] < 1.80:
        plt.figure()
        plot(run.prune_data[filenum],i)
        plt.title(str(count) + ', '+ str(i['result'].x[4])+ ', '+ str(i['val_acc']))
    count += 1

In [576]:
i = run_new_rand_d5[filenum][19]
plt.figure()
plot(run.prune_data[filenum],i,True)
plt.title(str(i['ci_deltaphi']) + ', '+ str(i['result'].x[4])+ ', '+ str(i['val_acc']))

In [366]:
t = run_new_rand_d7[filenum]
start = 5
length = 10
for i in t[start:start+length]:
    if i['val_acc']>0 and 0.16 < i['result'].x[4] < 1.80:
        plt.figure()
        plot(run.prune_data[filenum],i)
        plt.title(str(start) + ', '+ str(i['ci_deltaphi']) + ', '+ str(i['result'].x[4])+ ', '+ str(i['val_acc']))
    start += 1

In [90]:
(run.prune_data[filenum].fits[0].phase_l-run.prune_data[filenum].fits[0].phase_r)/np.pi

0.42191836371380759

In [82]:
hold = list()
for i in run.prune_data:
    for j in i.fits:
        hold.append((j.phase_l-j.phase_r)/np.pi%2)
plt.hist(hold)

(array([ 4.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  9.,  4.]),
 array([ 0.        ,  0.15024489,  0.30048979,  0.45073468,  0.60097958,
         0.75122447,  0.90146937,  1.05171426,  1.20195916,  1.35220405,
         1.50244895]),
 <a list of 10 Patch objects>)

In [218]:
bf = list()

In [304]:
filenum = 16

In [305]:
hold = list()
hold.append(csf(run_new_rand_d5[filenum][19]))
#hold.append(run.prune_data[filenum].fits[0].output_array())
#hold.append(csf(run_new_rand_d6[filenum][2]))
#hold.append([])
bf.append(np.array(hold))

In [306]:
len(bf)

17

In [378]:
run = Analysis.Run(np.load('73_Raw.npy'), np.load('73_Prune_new.npy'), Analysis.bval73, np.load('73bf_new.npy'))

In [ ]:
L = len(run.prune_data)
plt.rc('font', size=6)    
c = 1
  
fig = plt.figure(figsize=(20,20))
for i in run.prune_data:
    ax = plt.subplot(L,1,c)
    i.plot()
    for j in i.fits:
        j.plot(False)
    c += 1
plt.tight_layout()

In [605]:
L = len(run.prune_data)
plt.rc('font', size=6)    
c = 1
b = 2 
fig = plt.figure(figsize=(20,20))
for i in run.prune_data:
    ax = plt.subplot(round(float(L)/b),b,c)
    i.plot()
    for j in i.fits:
        j.plot(False)
    c += 1
plt.tight_layout()

In [606]:
fig.savefig('73 All fits',dpi=1200)

In [324]:
temp = list(bf[13][0])
temp = np.zeros(12)
bf[15] = np.array([np.array(temp)])

In [332]:
bf[10][0] = run.prune_data[10].fits[0].output_array()

In [331]:
run.prune_data[10].fits[0].output_array()

array([  6.23531275e-01,   6.58852736e-02,   8.23948569e+00,
         4.14459865e+00,   1.21505585e+01,   7.69458576e-06,
         3.69668637e-01,  -1.83529700e+01,  -1.03532800e+01,
         1.30344303e+00,   1.05780000e+04,  -1.43540600e+01])

# Computing Slips

In [599]:
run = Analysis.Run(np.load('73_Raw.npy'), np.load('73_Prune_new.npy'), Analysis.bval73, np.load('73bf_new.npy'))

In [391]:
se = list()

In [426]:
mom = 3
mindiff = 0.025
dV = 0.05
minsep = 0.3

In [569]:
filenum = 16

In [570]:
x = run.prune_data[filenum].x
y = run.prune_data[filenum].y
fit_hold = run.prune_data[filenum].fits
b = run.prune_data[filenum].b_val

In [571]:
temp = list(fr.countEdge(x,y,fit_hold,1,dV=dV,momentum=mom,minsep=minsep,mindiff = mindiff))

In [572]:
e = fr.findEdge(x,y,fit_hold,dV=dV,momentum=mom,mindiff = mindiff)

In [573]:
c = 0
for i in e:
    if len(i)>0:
        plt.figure()
        plt.plot(x,y)
        fit_hold[c].plot(False)
        for j in i:
            index = rcv.search(x,j[3])
            plt.plot(x[index],y[index],'c*',markersize=20)
            index = rcv.search(x,j[2])
            plt.plot(x[index],y[index],'y*',markersize=20)
            plt.title(j[0])
    c += 1

In [582]:
temp

[array([-20.398215  ,   1.        ,   1.20266313,   0.80586451]),
 array([-20.292575  ,   1.        ,   1.20266313,   0.80586451]),
 array([-18.525795  ,   1.        ,   1.20266313,   0.80586451]),
 array([-18.244665  ,   1.        ,   1.20266313,   0.80586451]),
 array([-18.143195  ,   1.        ,   1.20266313,   0.80586451]),
 array([-17.7641    ,   1.        ,   1.20266313,   0.80586451]),
 array([-17.64741   ,   1.        ,   1.20266313,   0.80586451]),
 array([-16.763765  ,   1.        ,   1.20266313,   0.80586451]),
 array([-16.70749   ,   1.        ,   1.20266313,   0.80586451])]

In [583]:
plt.figure()
plt.plot(x,y)
for i in temp:
    j = i[0]
    index = rcv.search(x,j)
    plt.plot(x[index],y[index],'y*',markersize=20)
    for k in fit_hold:
        k.plot(False)

In [555]:
del temp[-1]

In [473]:
temp[-2][0] = -17.1389

In [584]:
se.append(np.array(temp))

In [585]:
len(se)

17

In [581]:
for i in range(len(temp)):
    temp[i][2] = (fit_hold[0].phase_r-fit_hold[0].phase_l)/np.pi%2

In [566]:
temp = np.array([])

In [580]:
(fit_hold[0].phase_r-fit_hold[0].phase_l)/np.pi%2

1.2026631254379323

In [586]:
np.save('73se_new',se)

In [690]:
hold = list()
for i in se:
    for k in i:
        hold.append(2-k[2])

In [691]:
plt.rc('font', size=12)    
plt.hist(hold)
plt.xlabel('$\Delta\phi$ ($\pi$)')
plt.ylabel('Counts')

In [694]:
plt.savefig('73 Hist', dpi=1200)

In [693]:
np.std(hold)

0.073921788922506629

In [692]:
np.mean(hold)

0.65190729579890072

# Making Figures

In [7]:
run = Analysis.Run(np.load('73_Raw.npy'), np.load('73_Prune_new.npy'), Analysis.bval73, np.load('73bf_new.npy'))

In [610]:
filenum = 4
run.prune_data[filenum].plot()
run.prune_data[filenum].fits[0].plot()
run.prune_data[filenum].fits[1].plot()

In [623]:

fits_list = [[0,0],[1,1],[2,1],[4,0],[4,1],[5,0],[6,0],[7,0],[10,0]]
L = len(fits_list)
plt.rc('font', size=6)    
c = 1
b = 2 
fig = plt.figure(figsize=(20,20))
for k in fits_list:
    i = run.prune_data[k[0]]
    ax = plt.subplot(round(float(L)/b),b,c)
    i.plot_fit(k[1],False)
    c += 1
plt.tight_layout()

In [613]:
fig.savefig('73 Best Looking fits',dpi=1200)

In [614]:
bf = np.load('73bf_new.npy')

In [618]:
bf[7][0][7] = -20

In [620]:
run.prune_data[4].plot_fit(0,False)

In [695]:
fits_list = [[0,0],[2,1],[6,0],[7,0]]
L = len(fits_list)
plt.rc('font', size=12)    
c = 1
b = 2 
fig = plt.figure(figsize=(10,5))
for k in fits_list:
    i = run.prune_data[k[0]]
    ax = plt.subplot(round(float(L)/b),b,c)
    i.plot_fit(k[1],False)
    ax.annotate('{}$\pi$ $\Delta\phi$'.format(round(2-i.fits[k[1]].delta_phi,2)), xy=(0.01, 0.88), xycoords="axes fraction")
    if c == 1:
        ax.set_xticks([-28,-26,-24,-22])
        ax.set_yticks([12.0,12.1,12.2,12.3])
    if c == 2:
        ax.set_xticks([-26,-24,-22,-20])
        ax.set_yticks([12.0,12.1,12.2,12.3])
    if c == 3:
        ax.set_xticks([-26,-24,-22,-20,-18])
        ax.set_yticks([12.0,12.1,12.2])
        ax.set_ylabel('R$_D$ (k$\Omega$)') 
        ax.yaxis.set_label_coords(-0.15,1.1)
        ax.set_xlabel('V$_p$ (mV)')
        ax.xaxis.set_label_coords(1.1,-0.15)
    if c == 4:
        ax.set_xticks([-20,-18,-16,-14,-12,-10])
        ax.set_yticks([12.1,12.2,12.3])
    c += 1


In [696]:
fig.savefig('73 Phase Slips',dpi=1200)

In [689]:
filenum = -6
run.prune_data[filenum].plot()
for i in run.prune_data[filenum].fits:
    i.plot()

In [646]:
plt.tight_layout()

In [640]:
ax.xaxis.set_label_coords(1.05,-.2)

In [645]:
ax.yaxis.set_label_coords(-1.2,-.2)

In [697]:
plt.clf()

In [11]:
len(run.prune_data)

17

In [15]:
for i in run.prune_data:
    plt.figure()
    i.plot()

In [16]:
run.prune_data[9].plot()