In [1]:
import numpy as np
import matplotlib as mpl
import regression_cv as rcv
from matplotlib import pyplot as plt
import Analysis
from matplotlib.colors import LinearSegmentedColormap
%matplotlib

Using matplotlib backend: TkAgg


In [2]:
def search(seq, t):  
    min = 0
    max = len(seq) - 1
    while True:        
        m = (min + max) // 2
        if max <= min:
            if np.abs(t-seq[m]) < np.abs(t-seq[m-1]):          
                return m
            else:
                return m-1        
        if seq[m] < t:
            min = m + 1
        elif seq[m] > t:
            max = m - 1
        else:
            return m


def plot(data,result,full=False,if_data=True):
    x_min = result['x_min']
    x_max = result['x_max']
    if full:
        x = data.x
        y = data.y
    else:
        i_min = search(data.x,x_min)
        i_max = search(data.x,x_max)+1

        x = data.x[i_min:i_max]
        y = data.y[i_min:i_max]

    v0 = (x_min+x_max)/2.0

    params = result['result'].x
    model_l = params[0] + params[1] * np.sin(x*params[2] + (params[3]+params[4]*np.pi)) + params[5] * (x - v0)
    model_r = params[0] + params[1] * np.sin(x*params[2] + params[3]) + params[5] * (x - v0)
    if if_data:
        plt.plot(x,y)
    plt.plot(x,model_r,c='r')
    plt.plot(x,model_l,c='k')

In [3]:
def convert_scipy_fit(scipy_fit):
    x = scipy_fit['result'].x
    out = list()
    out.append(x[2])
    out.append(x[1])
    out.append(x[3]+x[4]*np.pi)
    out.append(x[3])
    out.append(x[0])
    out.append(x[5])
    out.append(1.0)
    out.append(scipy_fit['x_min'])
    out.append(scipy_fit['x_max'])
    out.append(x[4])
    out.append(1)
    out.append((scipy_fit['x_min'] + scipy_fit['x_max'])/2)
    return np.array(out)

In [19]:
run_reg = np.load('scipy_run.npy')
run_rand = np.load('scipy_run_rand_slope.npy')
#run_rand = np.load('2011_scipy_run_rand.npy')

In [10]:
run = Analysis.generate_2014()

In [487]:
#bf = np.load('52bf.npy')
bf = np.load('2011bf.npy')

In [453]:
#se = np.load('2011se.npy')
se = np.load('52se.npy')

In [1]:
filenum = 13

In [18]:
for i in range(len(run.prune_data[filenum].fits)):
    plt.figure()
    run.prune_data[filenum].plot_fit(i,False)
    print(run.prune_data[filenum].fits[i].delta_phi)

0.36051416396
1.38606761081
1.15009449262


In [22]:
t = run_rand[filenum]
count = 0
for i in t:
    if i['ci_deltaphi'] < 0.001 and 0.1 < i['result'].x[4] < 1.9:
        plt.figure()
        plot(run.prune_data[filenum],i)
        plt.title(str(count) + ', '+ str(i['ci_deltaphi']) + ', '+ str(i['result'].x[4]))
    count += 1

In [91]:
 run.prune_data[filenum].plot_fit(2)

In [15]:
plt.figure()
run.prune_data[filenum].plot()

In [10]:
i = 3
run.prune_data[filenum].plot()
plot(run.prune_data[filenum],run_rand[filenum][i],if_data=False)
run_rand[filenum][i]['result'].x

NameError: name 'run_rand' is not defined

In [205]:
run.prune_data[filenum].fits.append(Analysis.Fit(convert_scipy_fit(run_rand[filenum][12])))

In [18]:
run.prune_data[filenum].fits[0] = Analysis.Fit(convert_scipy_fit(run_rand[filenum][15]))

In [319]:
run.prune_data[filenum].fits[1] = run.prune_data[filenum].fits[0]

In [464]:
s = run.prune_data[filenum].slip_events(dV=0.06,minsep=3.0)
s

array([[-15.35117   ,   5.578     ,   1.22032794]])

In [2]:
#plt.figure()
d = run.prune_data[filenum]
#d.plot()
for i in s:
    y = d.y[search(d.x,i[0])]
    plt.scatter(i[0],y,s=50,c='orange')

NameError: name 'run' is not defined

In [245]:
list(se[1][:,1]).index(5.5275)

29

In [454]:
se[1]

array([[-14.86668   ,   5.5845    ,   1.09941899],
       [-11.9481    ,   5.5845    ,   1.09941899],
       [-11.8571    ,   5.5845    ,   1.09941899],
       [-11.343     ,   5.5845    ,   1.09941899],
       [-11.2408    ,   5.5845    ,   1.09941899],
       [ -8.7217645 ,   5.5835    ,   1.19018141],
       [ -8.467302  ,   5.583     ,   1.38606761],
       [ -8.366287  ,   5.583     ,   1.38606761],
       [ -6.119323  ,   5.583     ,   1.38606761],
       [ -5.242855  ,   5.583     ,   1.15009449],
       [ -5.0839935 ,   5.583     ,   1.15009449],
       [-14.554085  ,   5.5825    ,   0.96358912],
       [ -8.65831   ,   5.5825    ,   0.94004761],
       [ -7.607     ,   5.5825    ,   0.94004761],
       [ -7.36844   ,   5.5825    ,   0.94004761],
       [ -6.98      ,   5.5825    ,   0.94004761],
       [ -6.8358    ,   5.5825    ,   0.94004761],
       [-14.7602    ,   5.5815    ,   0.96816901],
       [-14.6023    ,   5.5815    ,   0.96816901],
       [-14.4301    ,   5.5815 

In [330]:
hold = list(se[2])


In [326]:
del hold[-2]

In [332]:
hold.append(s[0])

In [333]:
hold

[array([-37.78664   ,   5.536     ,   1.32371934]),
 array([-37.24676   ,   5.536     ,   1.32371934]),
 array([-36.8576    ,   5.536     ,   1.32371934]),
 array([-36.43507   ,   5.536     ,   1.32371934]),
 array([-36.135305  ,   5.536     ,   1.32371934]),
 array([-34.10375   ,   5.5295    ,   1.25167047]),
 array([-31.3739    ,   5.5295    ,   1.25167047]),
 array([-30.703555  ,   5.5295    ,   1.25167047]),
 array([-36.406475  ,   5.527     ,   1.20422528]),
 array([-35.36312   ,   5.527     ,   1.20422528]),
 array([-24.472575  ,   5.5265    ,   1.28183099]),
 array([-34.90141  ,   5.5255   ,   1.2278723])]

In [334]:
se[2] = np.array(hold)

In [335]:
np.save('2011se',se)

In [7]:
run.bvals

[5.5845,
 5.584,
 5.5835,
 5.583,
 5.5825,
 5.582,
 5.5815,
 5.581,
 5.5805,
 5.58,
 5.5795,
 5.579,
 5.5785,
 5.578,
 5.5775]

In [112]:
bf[filenum][0] = convert_scipy_fit(run_rand[filenum][11])

In [226]:
hold = list(bf[filenum])
#hold.append(convert_scipy_fit(run_rand[filenum][37]))

In [227]:
del hold[0]

In [228]:
bf[filenum] = np.array(hold)

In [230]:
np.save('2011bf',bf)

In [229]:
bf[filenum][:,9]

array([ 1.03406804,  0.24437509])

In [211]:
hold

[array([  6.56582994e-01,   1.52273267e-01,   3.88052788e+00,
          1.31914717e+01,   1.14747568e+01,   3.98574930e-05,
          3.85830631e-01,  -4.37885000e+01,  -2.98168700e+01,
          1.03623454e+00,   3.01800000e+03,  -3.67850300e+01])]

In [488]:
out = list()
for i in bf:
    if len(i)>0:
        for j in i:
            out.append([j[3]/np.pi%2,j[9]])
out = np.array(out)

In [489]:
plotColorizedHist(out,colors,bins=13)

In [490]:
np.mean(out[:,0])

0.86768848856477465

In [491]:
np.std(out[:,0])

0.6604381667971565

In [492]:
plt.ylim(0,6)

(0, 6)

In [493]:
plt.title('Phase Hist, mean = 0.87, std = 0.66')

In [494]:
plt.xlabel('Phase (Pi)')

In [495]:
plt.ylabel('Count')

In [496]:
plt.savefig('2011 Phase Hist Colorized')

In [462]:
count = -1
for i in bf:
    count += 1
    if len(i)>0:
        for j in i[:,1]:
            if abs(j) < 0.1:
                print count, 


13 13 14


In [301]:
x = np.arange(0.015,2.015,0.03)
normed = x/2.

norm = mpl.colors.Normalize(vmin=0, vmax=2)
colors = cmap(normed)

In [300]:
cdict = {'red':   ((0.0, 0.0, 0.0),
                   (0.125, 0.0, 0.0),
                   (0.17, 0.2, 0.2),
                   (0.4, 1, 1),
                   (0.5, 1.0, 1.0),
                   (0.7, 1.0, 1.0),
                   (0.8, 0.0, 0.0),
                  (1.0, 0.5, 0.5)),

         'green': ((0.0, 1, 1),
                   (0.1, 0.5, 0.5),
                   (0.135, 0.0, 0.0),
                   (0.4, 0.0, 0.0),
                   (0.5,0.0,0.0),
                   (0.65, 0.65, 0.65),
                   (0.8, 0.8, .8),
                  (1.0, 1, 1)),

         'blue':  ((0.0, 0.2, 0.2),
                   (0.13, 1.0, 1),
                   (0.135, .8, .8),
                   (0.17, 0.6, 0.6),
                   (0.35, 0.8, 0.8),
                   (0.5, 0.0, 0.0),
                   (0.85, 0, 0),
                   (1.0, 0.2, 0.2)),
        }
        
fullC = LinearSegmentedColormap('fullC', cdict)
cmap = fullC

In [347]:
def plotColorizedHist(items,colors,bins=10):
    items = np.array(items)
    _,a = np.histogram(items[:,0],bins=bins)
    w = a[1]-a[0]
    hold = list()
    for i in items:
        colorindex = int((i[1])/0.03)
        hold.append([i[0],colorindex])
    colorhold = [[] for i in range(len(colors))]
    for i in hold:
        colorhold[i[1]].append(i[0])
    temp = np.zeros(len(a)-1)
    for i in range(len(colorhold)):
        if len(colorhold[i]) == 0:
            continue
        y,_ = np.histogram(colorhold[i],a)
        plt.bar(a[:-1],y,bottom=temp,width=w,color=colors[i])
        temp+=y

In [460]:
len(bf)

15