In [1]:
import Analysis
import regression_cv as rcv
import numpy as np
import matplotlib as mpl
from matplotlib import pyplot as plt
%matplotlib

Using matplotlib backend: TkAgg


In [3]:
def csf(scipy_fit):
    x = scipy_fit['result'].x
    if x[4] > 1.5:
        dphi = 2-x[4]
    else:
        dphi = x[4]
    out = list()
    out.append(x[2])
    out.append(x[1])
    out.append(x[3]+x[4]*np.pi)
    out.append(x[3])
    out.append(x[0])
    out.append(x[5])
    out.append(1.0)
    out.append(scipy_fit['x_min'])
    out.append(scipy_fit['x_max'])
    out.append(dphi)
    out.append(1)
    out.append((scipy_fit['x_min'] + scipy_fit['x_max'])/2)
    return np.array(out)

In [2]:
run_d45 = np.load('2011_CV_smart_res_d45.npy')
run_d6 = np.load('2011_CV_smart_res_d6.npy')
run_d7 = np.load('2011_CV_smart_res_d7.npy')

In [3]:
run = Analysis.generate_2011()

In [5]:
for i in run.prune_data:
    plt.figure()
    i.plot()

In [5]:
bf_new = list()

In [167]:
filenum = 0

In [160]:
hold = list()
hold.append(run.prune_data[filenum].fits[0].output_array())
hold.append(run.prune_data[filenum].fits[1].output_array())
#hold.append(csf(run_d45[filenum][12]))
#hold.append(csf(run_d6[filenum][11]))
#hold.append(csf(run_d7[filenum][16]))
hold = np.array(np.array(hold))

In [154]:
bf_new.append(hold)

In [155]:
len(bf_new)

22

In [148]:
hold = np.array([])

In [136]:
plt.figure()
n = 16
i = run_d7[filenum][n]
rcv.plot(run.prune_data[filenum], i,full=True)
plt.title(str(i['val_acc']) + ', ' + str(i['ci_deltaphi']) + ', '+ str(i['result'].x[4]))


In [169]:
for i in run.prune_data[filenum].fits:
    plt.figure()
    run.prune_data[filenum].plot()
    i.plot('False')
    print(i.delta_phi)

1.3237193395


In [337]:
np.save('2011bf_new_residual',bf_new)

In [7]:
bval2011 = run.bvals

run_new = Analysis.Run(np.load('2011_Raw.npy'), np.load('2011_Prune.npy'), bval2011, np.load('2011bf_new_residual.npy'))

In [571]:
filenum = 4

In [8]:
for j in range(len(run_new.prune_data)):
    if len(run_new.prune_data[j].fits) > 0:
        for i in range(len(run_new.prune_data[j].fits)):
            plt.figure()
            run_new.prune_data[j].plot_fit(i,False)
            plt.title('Filenum: '+str(j)+' Fit: '+str(i)+' Phase: ' + str(run_new.prune_data[j].fits[i].delta_phi))

c:\winpython\python-2.7.10.amd64\lib\site-packages\matplotlib\pyplot.py:524: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)


In [476]:
bf_new = np.load('2014bf_new_residual.npy')

In [576]:
run_new.prune_data[filenum].plot_fit(0,False)

In [499]:
bf_new[filenum][0][8] = -6.93102

In [573]:
hold = run_new.prune_data[filenum].sorted_slip_events(dV=0.07,minsep=3.0)
hold

[array([], dtype=float64), array([[-21.65668   ,   5.5825    ,   1.02110047],
        [-14.231805  ,   5.5825    ,   1.02110047]]), array([], dtype=float64)]

In [596]:
hold[1][5][0] = -6.98363

In [587]:
hold[1] = np.array(hold[1])

In [597]:
hold[1]

array([[-14.5373    ,   5.5825    ,   1.02110047],
       [ -9.12977   ,   5.5825    ,   1.02110047],
       [ -8.65187   ,   5.5825    ,   1.02110047],
       [ -7.6015    ,   5.5825    ,   1.02110047],
       [ -7.3762    ,   5.5825    ,   1.02110047],
       [ -6.98363   ,   5.5825    ,   1.02110047]])

In [486]:
out_best = np.load('2014se_new_residual.npy')

In [606]:
np.save('2014se_new_residual',out_best)

In [607]:
np.save('2014bf_new_residual', bf_new)

In [200]:
out_best = list()

In [339]:
out = list()
for i in run_new.prune_data:
    out.append(i.sorted_slip_events(dV=0.07,minsep=3.0))

In [409]:
filenum += 1

In [410]:
print(out[filenum])
d = run_new.prune_data[filenum]
d.plot()
for k in d.fits:
    k.plot(False)
for j in out[filenum]:
    for i in j:
        y = d.y[rcv.search(d.x,i[0])]
        plt.scatter(i[0],y,s=50,c='orange')

IndexError: list index out of range

In [408]:
out_best.append(np.array(out[filenum]))

In [400]:
out[filenum][1] = np.array(hold)

In [397]:
hold = list(out[filenum][1])

In [360]:
hold[0][0]=-24.8579

In [399]:
np.array(hold)

array([[-24.472575  ,   5.5265    ,   1.28183099],
       [-35.665255  ,   5.5265    ,   0.99712247]])

In [398]:
del hold[-1]

In [297]:
filenum

10

In [260]:
bval2014[13]

5.578

In [264]:
out[filenum]

[array([], dtype=float64),
 array([-21.7414    ,   5.578     ,   1.05390399]),
 array([], dtype=float64)]

In [266]:
out_best[filenum] = out[filenum]

In [456]:
np.save('2011se_new_residual',out_best)

In [287]:
p = list()
for i in out_best[:,1]:
    if len(i)>0:
        p.extend(i)

In [374]:
bf_new[filenum]

array([[  6.98810787e-01,   1.32284485e-01,   8.13085827e+00,
          2.53390783e+00,   1.13042891e+01,  -1.00000000e-03,
          1.00000000e+00,  -3.31195430e+01,  -2.11195430e+01,
          2.18435344e-01,   1.00000000e+00,  -2.71195430e+01],
       [  6.96756980e-01,   1.10507769e-01,   4.67112466e+00,
          1.55621996e+00,   1.13010182e+01,   8.64632000e-04,
          1.00000000e+00,  -4.28038286e+01,  -2.88038286e+01,
          9.91504961e-01,   1.00000000e+00,  -3.58038286e+01]])

In [447]:
hold = np.array(out_best[1])

In [450]:
hold[1] = np.array([])

In [578]:
out_best[4]

array([array([[-21.76582   ,   5.5825    ,   0.27023909]]),
       array([[-14.174145  ,   5.5825    ,   1.00736273]]),
       array([], dtype=float64)], dtype=object)

In [602]:
p = list()
q = list()
for i in out_best:
    for j in i:
        if len(j) > 0:
            for k in j:
                if k[2] > 0.75:
                    p.append(k)
                else:
                    q.append(k)

In [603]:
p

[array([-14.86668   ,   5.5845    ,   1.09941899]),
 array([-14.5373    ,   5.5825    ,   1.02110047]),
 array([-9.12977   ,  5.5825    ,  1.02110047]),
 array([-8.65187   ,  5.5825    ,  1.02110047]),
 array([-7.6015    ,  5.5825    ,  1.02110047]),
 array([-7.3762    ,  5.5825    ,  1.02110047]),
 array([-6.98363   ,  5.5825    ,  1.02110047]),
 array([-14.0051    ,   5.581     ,   1.01118957]),
 array([-7.89479   ,  5.581     ,  1.01118957]),
 array([-7.63179   ,  5.581     ,  1.01118957]),
 array([-7.42065   ,  5.581     ,  1.01118957]),
 array([-7.22062   ,  5.581     ,  1.01118957]),
 array([-13.737655 ,   5.5805   ,   0.9785673]),
 array([-13.788005  ,   5.58      ,   0.99118949]),
 array([-7.4022255 ,  5.58      ,  0.99118949]),
 array([-7.04453   ,  5.58      ,  0.99118949]),
 array([-6.8631355 ,  5.58      ,  0.99118949]),
 array([-21.7414    ,   5.578     ,   1.05390399])]

In [604]:
se2014 = np.array([np.array(q),np.array(p)])

In [605]:
np.save('2014se_new',se2014)

In [564]:
res = np.load('2014_4.npy')

In [565]:
res

array([  6.31826683e-01,   2.12189093e-01,   2.57649049e+00,
        -6.31391229e-01,   1.11720267e+01,  -7.18277235e-04,
         1.00000000e+00,  -2.27612000e+01,  -6.69808000e+00,
         1.02110047e+00,   1.00000000e+00,  -1.47296400e+01])

In [569]:
bf_new[filenum][0] = res

In [567]:
filenum

4