In [1]:
import Analysis
import numpy as np
import matplotlib as mpl
from matplotlib import pyplot as plt
from matplotlib.gridspec import GridSpec
import regression_cv as rcv

import FitRoutine2 as fr

In [2]:
%matplotlib

Using matplotlib backend: TkAgg


In [3]:
run14 = Analysis.Run(np.load('2014_Raw.npy'), np.load('2014_Prune_new.npy'), Analysis.bval2011, np.load('2014bf_new_prune_edit.npy'))

In [4]:
run11 = Analysis.Run(np.load('2011_Raw.npy'), np.load('2011_Prune_new_flat.npy'), Analysis.bval2011, np.load('2011bf_new_prune_flat_edit.npy'))

In [5]:
angles = []
mod_angles = []

In [6]:
for i in run14.prune_data:
    for j in i.fits:
        angles.append((j.phase_r-j.phase_l)/np.pi)
        mod_angles.append((j.phase_r-j.phase_l)/np.pi%2)

In [33]:
for i in run11.prune_data:
    for j in i.fits:
        angles.append((j.phase_r-j.phase_l)/np.pi)
        mod_angles.append((j.phase_r-j.phase_l)/np.pi%2)

In [8]:
plt.figure()
plt.hist(angles,bins=60)

(array([ 9.,  7.,  2.,  1.,  2.,  3.,  1.,  0.,  2.,  5.,  0.,  9.,  8.,
         5.,  2.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
         1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  2.,  3.,  1.,  0.,  0.,
         0.,  0.,  0.,  0.,  1.,  0.,  1.,  1.,  2.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]),
 array([-1.78437834, -1.72584664, -1.66731495, -1.60878325, -1.55025155,
        -1.49171985, -1.43318816, -1.37465646, -1.31612476, -1.25759306,
        -1.19906136, -1.14052967, -1.08199797, -1.02346627, -0.96493457,
        -0.90640287, -0.84787118, -0.78933948, -0.73080778, -0.67227608,
        -0.61374438, -0.55521269, -0.49668099, -0.43814929, -0.37961759,
        -0.3210859 , -0.2625542 , -0.2040225 , -0.1454908 , -0.0869591 ,
        -0.02842741,  0.03010429,  0.08863599,  0.14716769,  0.20569939,
         0.26423108,  0.32276278,  0.38129448,  0.43982618,  0.49835787,
         0.55688957,  0.61542127,  0.67395297,  0.73248467,  0.79101636,
 

In [34]:
plt.figure()
plt.hist(mod_angles,bins=60)

(array([  1.,   1.,   4.,  11.,  10.,   1.,   1.,   3.,   0.,   2.,   0.,
          2.,   3.,   2.,   1.,   1.,   0.,   0.,   0.,   1.,   1.,   1.,
          2.,   6.,   1.,   0.,   0.,  10.,   7.,  12.,   3.,   7.,   2.,
          3.,   0.,   0.,   0.,   2.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   1.,   0.,   3.]),
 array([ 0.17118999,  0.1973171 ,  0.22344421,  0.24957132,  0.27569843,
         0.30182554,  0.32795265,  0.35407976,  0.38020687,  0.40633398,
         0.43246109,  0.4585882 ,  0.48471531,  0.51084242,  0.53696953,
         0.56309664,  0.58922375,  0.61535086,  0.64147797,  0.66760509,
         0.6937322 ,  0.71985931,  0.74598642,  0.77211353,  0.79824064,
         0.82436775,  0.85049486,  0.87662197,  0.90274908,  0.92887619,
         0.9550033 ,  0.98113041,  1.00725752,  1.03338463,  1.05951174,
         1.08563885,  1.11176596,  1.13789307,  1.16402018,  1.19014729,
      

In [10]:
bf14 = np.load('2014bf_new_prune_edit.npy')
se14 = np.load('2014se_edit.npy')

In [28]:
se14_new = list()
for i in range(len(se14)):
    temp = list()
    for j in se14[i]:
        fit = bf14[i][abs(bf14[i][:,9]-j[2])<0.01]
        if len(fit)==0:
            print(i,j)
            continue
        else:
            fit = fit[0]
        new_phase = (fit[3] - fit[2])/np.pi%2
        hold = np.array(j)
        hold[2] = new_phase
        temp.append(hold)
    se14_new.append(np.array(temp))

In [74]:
np.save('2014se_new_sign',np.array(se14_new))

In [38]:
bf11 = np.load('2011bf_new_prune_flat_edit.npy')
se11 = np.load('2011se_flat_edit.npy')

In [56]:
se11_new = list()
for i in range(len(se11)):
    temp = list()
    for j in se11[i]:
        fit = bf11[i][abs(bf11[i][:,9]-j[2])<0.01]
        if len(fit)==0:
            print(i,j)
            continue
        else:
            fit = fit[0]
        new_phase = (fit[3] - fit[2])/np.pi%2
        hold = np.array(j)
        hold[2] = new_phase
        temp.append(hold)
    se11_new.append(np.array(temp))

In [73]:
np.save('2011se_new_sign',np.array(se11_new))

In [75]:
temp = list()
for i in se11_new:
    if len(i)>0:
        temp.extend(i[:,2])

In [77]:
bins = np.arange(0.0,2.0,0.03)
plt.hist(temp,bins)

(array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   3.,   4.,  21.,   0.,
          0.,  10.,   1.,   0.,   1.,   2.,   5.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   1.,   7.,   0.,   0.,   4.,  15.,  13.,   2.,
          1.,   3.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]),
 array([ 0.  ,  0.03,  0.06,  0.09,  0.12,  0.15,  0.18,  0.21,  0.24,
         0.27,  0.3 ,  0.33,  0.36,  0.39,  0.42,  0.45,  0.48,  0.51,
         0.54,  0.57,  0.6 ,  0.63,  0.66,  0.69,  0.72,  0.75,  0.78,
         0.81,  0.84,  0.87,  0.9 ,  0.93,  0.96,  0.99,  1.02,  1.05,
         1.08,  1.11,  1.14,  1.17,  1.2 ,  1.23,  1.26,  1.29,  1.32,
         1.35,  1.38,  1.41,  1.44,  1.47,  1.5 ,  1.53,  1.56,  1.59,
         1.62,  1.65,  1.68,  1.71,  1.74,  1.77,  1.8 ,  1.83,  1.86,
         1.89,  1.92,  1.95,  1.98]),
 <a list of 66 Patc

In [ ]:
se11_new[9]

In [ ]:
se11[9]

In [ ]:
(bf11[9][0][3]-bf11[9][0][2])/np.pi*np.ones(5)

In [ ]:
se11_new[9][0:5][:,2] = (bf11[9][0][3]-bf11[9][0][2])/np.pi*np.ones(5)

In [ ]:
run14.prune_data[5].plot_fit(2)

In [ ]:
bf14 = np.load('2014bf_new_prune_edit.npy')

In [ ]:
se11_new_windowed = list()
for i in range(len(se11_new)):
    temp = list()
    for j in se11_new[i]:
        hold = np.array(j)
        if -1.89<j[2]<-0.5:
            hold[2] = 2 + j[2]
        elif 1.42<j[2]<2:
            hold[2] = j[2] - 2
        temp.append(hold)
    se11_new_windowed.append(np.array(temp))

In [ ]:
se14_new_windowed = list()
for i in range(len(se14_new)):
    temp = list()
    for j in se14_new[i]:
        hold = np.array(j)
        if -1.89<j[2]<-0.5:
            hold[2] = 2 + j[2]
        elif 1.42<j[2]<2:
            hold[2] = j[2] - 2
        temp.append(hold)
    se14_new_windowed.append(np.array(temp))

In [ ]:
np.save('2011se_new_sign_windowed',np.array(se11_new_windowed))
np.save('2014se_new_sign_windowed',np.array(se14_new_windowed))

In [ ]:
run11.prune_data[0].plot_fit(1)

In [ ]:
se11 = np.load('2011se_new_sign.npy')
se14 = np.load('2014se_new_sign.npy')

In [ ]:
se11[0]

In [ ]:
set(se11_new[0][:,2])

In [ ]:
hold11 = list()
for i in se11_new:
    if len(i) > 0:
        for k in list(set(i[:,2])):
            hold11.append(k%2)

hold14 = list()
for i in se14_new:
    if len(i) > 0:
        for k in list(set(i[:,2])):
            hold11.append(k%2)

In [ ]:
plt.hist(hold11)

In [ ]:
solo_slips = list()
for i in hold11:
    solo_slips.append(i)
for i in hold14:
    solo_slips.append(i)

In [ ]:
bins = np.arange(0,2.0,0.03)
plt.hist(solo_slips,bins)
plt.xlabel('$\Delta\phi$ ($\pi$)')
plt.ylabel('Count')