In [11]:
import Analysis
import numpy as np
import matplotlib as mpl
from matplotlib import pyplot as plt
from matplotlib.gridspec import GridSpec
import regression_cv as rcv
%matplotlib

import copy
import FitRoutine2 as fr

Using matplotlib backend: TkAgg


In [123]:
bf_hold = list()

In [7]:
def parseData():
    f = open('filenames')
    raw = f.read()
    parse = raw.split('\n',-1)
    out = list()
    f.close()
    n = 0
    for i in parse:
        if i == '':
            continue
        f = open('C:\\Users\\Simas\Desktop\\Simon Matlab\\matlab\\'+str(i), 'r')
        raw = f.readline()
        parse = raw.split('\r',-1)
        data =np.ndarray(shape=(2,len(parse)-2))   
        count = 0
        for a in parse: 
            if count > 0 and count < (len(parse)-1):
                hold = a.split('\t',-1)                    
                data[0,count-1]=float(hold[0])
                data[1,count-1]=float(hold[1])
            count += 1
        if data[0,0]>data[0,-1]:
            print(n, "Right to Left")
        else:
            print(n, "Left to Right")
        n += 1
        

In [186]:
run = Analysis.Run(np.load('2014_Raw.npy'), np.load('2014_Prune_new.npy'), Analysis.bval2014, np.load('2014bf_new_prune.npy'))

In [187]:
n = 10

i = run.prune_data[n]
for j in i.fits:
    fig = plt.figure()
    i.plot()
    j.plot(False,linewidth=2)
    plt.xlim(min(i.x),max(i.x))

In [101]:
m = 2

In [102]:
i.fits[m].phase_l/np.pi

1.7108123569258853

In [103]:
i.fits[m].phase_r/np.pi

0.3949201884574931

In [104]:
i.fits[m].delta_phi

1.3158921684683922

In [72]:
(i.fits[m].phase_l-i.fits[m].phase_r)/np.pi

1.4196261002201402

In [188]:
hold = list()
for j in i.fits:
    hold.append(j.output_array())


In [156]:
hold[0][9] = 2 - hold[0][9] 

In [177]:
bf_hold.append(np.array(hold))

In [98]:
hold

[array([  6.70203152e-01,   2.26564040e-01,   5.84104802e+00,
          1.38116109e+00,   1.14416245e+01,  -9.88711670e-04,
          1.00000000e+00,  -1.40747910e+01,  -4.07479100e+00,
          5.80373900e-01,   3.27045723e-04,  -9.07479100e+00]),
 array([  8.00000000e-01,   2.43506167e-01,   1.11099727e+01,
          5.48913321e+00,   1.14823015e+01,  -1.00000000e-03,
          1.00000000e+00,  -2.69126722e+01,  -1.69126722e+01,
          2.10831209e-01,   1.41780271e-04,  -2.19126722e+01])]

In [178]:
len(bf_hold)

15

In [120]:
del bf_hold[-1]

In [191]:
np.save('2014_bf_new_prune_phi_adjusted.npy',bf_hold)

In [192]:
run = Analysis.Run(np.load('2014_Raw.npy'), np.load('2014_Prune_new.npy'), Analysis.bval2014, np.load('2014_bf_new_prune_phi_adjusted.npy'))

In [198]:
m = 0
for i in run.prune_data:
    if len(i.fits) > m:
        m = len(i.fits)

L = len(run.prune_data)
total = L*m
c = 1
n = 0
plt.rc('font', size=6)    
bins = np.arange(0.0,2.03,0.03)
fig = plt.figure(figsize=(20,50))
for i in run.prune_data:
    temp = 0
    for j in i.fits:
        ax = plt.subplot(L,m,c)
        i.plot()
        j.plot(False)
        plt.xlim([min(i.x),max(i.x)])
        ax.set_title("{}$\pi$ $\Delta\phi$".format(round(j.delta_phi,4)))
        #ax.annotate("{}$\pi$ $\Delta\phi$".format(round(j.delta_phi,4)), xy=(0.72, 0.80), xycoords="axes fraction")
        c += 1
        temp += 1
    c += (m-temp)
    n += 1
fig.tight_layout()

In [199]:
fig.savefig('2014 Updated Phase Direction',dpi=1000)

In [200]:
filenum = 2

In [235]:
x = run.prune_data[filenum].x
y = run.prune_data[filenum].y
fit_hold = run.prune_data[filenum].fits

In [236]:
fe = fr.findEdge(x,y,fit_hold,dV=0.09,mindiff=0.03)

In [237]:
c = 0
for i in fe:
    if len(i)>0:
        plt.figure()
        plt.plot(x,y)
        fit_hold[c].plot(False)
        for j in i:
            index = rcv.search(x,j[3])
            plt.plot(x[index],y[index],'c*',markersize=20)
            index = rcv.search(x,j[2])
            plt.plot(x[index],y[index],'y*',markersize=20)
    c += 1

In [238]:
plt.figure()
plt.plot(x,y)
fs = fr.finalSlips(x,y,fit_hold,dV=0.09,mindiff=0.04,minsep=1.0)
for j in fs:
    for i in j:
        index = rcv.search(x,(i[2]+i[3])/2)
        plt.plot(x[index],y[index],'c*',markersize=20)

In [239]:
fs

array([ array([[  1.2706656 ,   1.        ,  -9.032474  ,  -8.861581  ,   1.        ],
       [  0.28183099,   2.        , -18.22453   , -18.21787   ,   1.        ],
       [  0.28183099,   1.        , -17.76524   , -17.75465   ,   1.        ],
       [  0.28183099,   2.        , -17.48594   , -17.44195   ,   1.        ],
       [  1.72068398,   1.        , -19.67621   , -19.48347   ,   1.        ],
       [  1.31589217,   1.        , -27.4663    , -27.2781    ,   1.        ],
       [  1.31589217,   2.        , -25.80974   , -25.79647   ,   1.        ],
       [  1.31589217,   1.        , -25.28289   , -25.27593   ,   1.        ],
       [  1.31589217,   2.        , -25.13437   , -25.01768   ,   1.        ],
       [  1.31589217,   1.        , -24.37667   , -24.37529   ,   1.        ]]),
       array([], dtype=float64), array([], dtype=float64),
       array([], dtype=float64)], dtype=object)

In [231]:
se = np.load('2014se_new_prune_09dV.npy')

In [260]:
filenum = 8

In [261]:
n = 0

In [262]:
a = 2 - run.prune_data[filenum].fits[n].delta_phi
print(a)

0.354462291403


In [263]:
np.where(se[0][:,2]==a)

(array([31, 32, 37, 38], dtype=int64),)

In [265]:
se[0][38]

array([-26.6204    ,   5.5805    ,   0.35446229])

In [269]:
se[0][38][2] = 2 - se[0][38][2]

In [270]:
np.save('2014se_new_prune_phi_adjusted.npy',se)

In [275]:
se_b = list()
test = np.vstack((se[0],se[1]))
for i in run.bvals:
    se_b.append(test[[test[:,1]==i]])
se_b = np.array(se_b)


m = 0
for i in run.prune_data:
    if len(i.fits) > m:
        m = len(i.fits)
m+=1 #hist
        
        
L = len(run.prune_data)
total = L*m
c = 1
n = 0
plt.rc('font', size=6)    
bins = np.arange(0.0,2.03,0.03)
fig = plt.figure(figsize=(20,50))
for i in run.prune_data:
    temp = 0
    for j in i.fits:
        ax = plt.subplot(L,m,c)
        i.plot()
        j.plot(False)
        plt.xlim([min(i.x),max(i.x)])
        for k in se_b[n][se_b[n][:,2] == j.delta_phi]:
            ax.axvline(k[0],color='k',lw=1)
        c += 1
        temp += 1
    ax = plt.subplot(L,m,c)
    plt.hist(se_b[n][:,2], bins=bins)
    plt.xlim([0,2.0])
    plt.xticks([0,0.25,0.5,1.0,1.25,1.5])
    c += (m-temp)
    n += 1
fig.tight_layout()

In [276]:
fig.savefig('2014 Fit and Slips 09dV updated phase values',dpi=1000)